// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Execute(ctx context.Context, name string, args ...string) ([]byte, error) {
	// string
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) Execute(ctx interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_Execute_Call {
	return &MockCommandExecutor_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandExecutor_Execute_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) Return(bytes []byte, err error) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) RunAndReturn(run func(ctx context.Context, name string, args ...string) ([]byte, error)) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Run(ctx context.Context, name string, args ...string) error {
	// string
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) Run(ctx interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_Run_Call {
	return &MockCommandExecutor_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandExecutor_Run_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Run_Call) Return(err error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandExecutor_Run_Call) RunAndReturn(run func(ctx context.Context, name string, args ...string) error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}
