// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/models"
	"github.com/hirakiuc/gh-orbit/internal/triage"
	"github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApplyNotificationBatchLocally provides a mock function for the type MockRepository
func (_mock *MockRepository) ApplyNotificationBatchLocally(ctx context.Context, request types.NotificationBatchRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ApplyNotificationBatchLocally")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NotificationBatchRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApplyNotificationBatchLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyNotificationBatchLocally'
type MockRepository_ApplyNotificationBatchLocally_Call struct {
	*mock.Call
}

// ApplyNotificationBatchLocally is a helper method to define mock.On call
//   - ctx context.Context
//   - request types.NotificationBatchRequest
func (_e *MockRepository_Expecter) ApplyNotificationBatchLocally(ctx any, request any) *MockRepository_ApplyNotificationBatchLocally_Call {
	return &MockRepository_ApplyNotificationBatchLocally_Call{Call: _e.mock.On("ApplyNotificationBatchLocally", ctx, request)}
}

func (_c *MockRepository_ApplyNotificationBatchLocally_Call) Run(run func(ctx context.Context, request types.NotificationBatchRequest)) *MockRepository_ApplyNotificationBatchLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.NotificationBatchRequest
		if args[1] != nil {
			arg1 = args[1].(types.NotificationBatchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ApplyNotificationBatchLocally_Call) Return(err error) *MockRepository_ApplyNotificationBatchLocally_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApplyNotificationBatchLocally_Call) RunAndReturn(run func(ctx context.Context, request types.NotificationBatchRequest) error) *MockRepository_ApplyNotificationBatchLocally_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveThread provides a mock function for the type MockRepository
func (_mock *MockRepository) ArchiveThread(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ArchiveThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveThread'
type MockRepository_ArchiveThread_Call struct {
	*mock.Call
}

// ArchiveThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) ArchiveThread(ctx any, id any) *MockRepository_ArchiveThread_Call {
	return &MockRepository_ArchiveThread_Call{Call: _e.mock.On("ArchiveThread", ctx, id)}
}

func (_c *MockRepository_ArchiveThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_ArchiveThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ArchiveThread_Call) Return(err error) *MockRepository_ArchiveThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ArchiveThread_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_ArchiveThread_Call {
	_c.Call.Return(run)
	return _c
}

// EnrichNotification provides a mock function for the type MockRepository
func (_mock *MockRepository) EnrichNotification(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error {
	ret := _mock.Called(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for EnrichNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_EnrichNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichNotification'
type MockRepository_EnrichNotification_Call struct {
	*mock.Call
}

// EnrichNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - nodeID string
//   - body string
//   - author string
//   - htmlURL string
//   - resourceState string
//   - resourceSubState string
func (_e *MockRepository_Expecter) EnrichNotification(ctx any, id any, nodeID any, body any, author any, htmlURL any, resourceState any, resourceSubState any) *MockRepository_EnrichNotification_Call {
	return &MockRepository_EnrichNotification_Call{Call: _e.mock.On("EnrichNotification", ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)}
}

func (_c *MockRepository_EnrichNotification_Call) Run(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string)) *MockRepository_EnrichNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockRepository_EnrichNotification_Call) Return(err error) *MockRepository_EnrichNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_EnrichNotification_Call) RunAndReturn(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error) *MockRepository_EnrichNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetBridgeHealth provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBridgeHealth(ctx context.Context) (*models.BridgeHealth, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *models.BridgeHealth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.BridgeHealth, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.BridgeHealth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BridgeHealth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeHealth'
type MockRepository_GetBridgeHealth_Call struct {
	*mock.Call
}

// GetBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetBridgeHealth(ctx any) *MockRepository_GetBridgeHealth_Call {
	return &MockRepository_GetBridgeHealth_Call{Call: _e.mock.On("GetBridgeHealth", ctx)}
}

func (_c *MockRepository_GetBridgeHealth_Call) Run(run func(ctx context.Context)) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetBridgeHealth_Call) Return(bridgeHealth *models.BridgeHealth, err error) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Return(bridgeHealth, err)
	return _c
}

func (_c *MockRepository_GetBridgeHealth_Call) RunAndReturn(run func(ctx context.Context) (*models.BridgeHealth, error)) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotification provides a mock function for the type MockRepository
func (_mock *MockRepository) GetNotification(ctx context.Context, id string) (*triage.NotificationWithState, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *triage.NotificationWithState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*triage.NotificationWithState, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *triage.NotificationWithState); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*triage.NotificationWithState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetNotification(ctx any, id any) *MockRepository_GetNotification_Call {
	return &MockRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", ctx, id)}
}

func (_c *MockRepository_GetNotification_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetNotification_Call) Return(notificationWithState *triage.NotificationWithState, err error) *MockRepository_GetNotification_Call {
	_c.Call.Return(notificationWithState, err)
	return _c
}

func (_c *MockRepository_GetNotification_Call) RunAndReturn(run func(ctx context.Context, id string) (*triage.NotificationWithState, error)) *MockRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncMeta provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSyncMeta(ctx context.Context, userID string, key string) (*models.SyncMeta, error) {
	ret := _mock.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncMeta")
	}

	var r0 *models.SyncMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.SyncMeta, error)); ok {
		return returnFunc(ctx, userID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.SyncMeta); ok {
		r0 = returnFunc(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SyncMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncMeta'
type MockRepository_GetSyncMeta_Call struct {
	*mock.Call
}

// GetSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *MockRepository_Expecter) GetSyncMeta(ctx any, userID any, key any) *MockRepository_GetSyncMeta_Call {
	return &MockRepository_GetSyncMeta_Call{Call: _e.mock.On("GetSyncMeta", ctx, userID, key)}
}

func (_c *MockRepository_GetSyncMeta_Call) Run(run func(ctx context.Context, userID string, key string)) *MockRepository_GetSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetSyncMeta_Call) Return(syncMeta *models.SyncMeta, err error) *MockRepository_GetSyncMeta_Call {
	_c.Call.Return(syncMeta, err)
	return _c
}

func (_c *MockRepository_GetSyncMeta_Call) RunAndReturn(run func(ctx context.Context, userID string, key string) (*models.SyncMeta, error)) *MockRepository_GetSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function for the type MockRepository
func (_mock *MockRepository) ListNotifications(ctx context.Context) ([]triage.NotificationWithState, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []triage.NotificationWithState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]triage.NotificationWithState, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []triage.NotificationWithState); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]triage.NotificationWithState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListNotifications(ctx any) *MockRepository_ListNotifications_Call {
	return &MockRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx)}
}

func (_c *MockRepository_ListNotifications_Call) Run(run func(ctx context.Context)) *MockRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListNotifications_Call) Return(notificationWithStates []triage.NotificationWithState, err error) *MockRepository_ListNotifications_Call {
	_c.Call.Return(notificationWithStates, err)
	return _c
}

func (_c *MockRepository_ListNotifications_Call) RunAndReturn(run func(ctx context.Context) ([]triage.NotificationWithState, error)) *MockRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotifiedBatch provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkNotifiedBatch(ctx context.Context, ids []string) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotifiedBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkNotifiedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotifiedBatch'
type MockRepository_MarkNotifiedBatch_Call struct {
	*mock.Call
}

// MarkNotifiedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) MarkNotifiedBatch(ctx any, ids any) *MockRepository_MarkNotifiedBatch_Call {
	return &MockRepository_MarkNotifiedBatch_Call{Call: _e.mock.On("MarkNotifiedBatch", ctx, ids)}
}

func (_c *MockRepository_MarkNotifiedBatch_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkNotifiedBatch_Call) Return(err error) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkNotifiedBatch_Call) RunAndReturn(run func(ctx context.Context, ids []string) error) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReadLocally provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkReadLocally(ctx context.Context, id string, isRead bool) error {
	ret := _mock.Called(ctx, id, isRead)

	if len(ret) == 0 {
		panic("no return value specified for MarkReadLocally")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isRead)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkReadLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReadLocally'
type MockRepository_MarkReadLocally_Call struct {
	*mock.Call
}

// MarkReadLocally is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isRead bool
func (_e *MockRepository_Expecter) MarkReadLocally(ctx any, id any, isRead any) *MockRepository_MarkReadLocally_Call {
	return &MockRepository_MarkReadLocally_Call{Call: _e.mock.On("MarkReadLocally", ctx, id, isRead)}
}

func (_c *MockRepository_MarkReadLocally_Call) Run(run func(ctx context.Context, id string, isRead bool)) *MockRepository_MarkReadLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkReadLocally_Call) Return(err error) *MockRepository_MarkReadLocally_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkReadLocally_Call) RunAndReturn(run func(ctx context.Context, id string, isRead bool) error) *MockRepository_MarkReadLocally_Call {
	_c.Call.Return(run)
	return _c
}

// MuteThread provides a mock function for the type MockRepository
func (_mock *MockRepository) MuteThread(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MuteThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MuteThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MuteThread'
type MockRepository_MuteThread_Call struct {
	*mock.Call
}

// MuteThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) MuteThread(ctx any, id any) *MockRepository_MuteThread_Call {
	return &MockRepository_MuteThread_Call{Call: _e.mock.On("MuteThread", ctx, id)}
}

func (_c *MockRepository_MuteThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_MuteThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MuteThread_Call) Return(err error) *MockRepository_MuteThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MuteThread_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_MuteThread_Call {
	_c.Call.Return(run)
	return _c
}

// SetHandledLocally provides a mock function for the type MockRepository
func (_mock *MockRepository) SetHandledLocally(ctx context.Context, id string, isHandled bool) error {
	ret := _mock.Called(ctx, id, isHandled)

	if len(ret) == 0 {
		panic("no return value specified for SetHandledLocally")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isHandled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetHandledLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHandledLocally'
type MockRepository_SetHandledLocally_Call struct {
	*mock.Call
}

// SetHandledLocally is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isHandled bool
func (_e *MockRepository_Expecter) SetHandledLocally(ctx any, id any, isHandled any) *MockRepository_SetHandledLocally_Call {
	return &MockRepository_SetHandledLocally_Call{Call: _e.mock.On("SetHandledLocally", ctx, id, isHandled)}
}

func (_c *MockRepository_SetHandledLocally_Call) Run(run func(ctx context.Context, id string, isHandled bool)) *MockRepository_SetHandledLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetHandledLocally_Call) Return(err error) *MockRepository_SetHandledLocally_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetHandledLocally_Call) RunAndReturn(run func(ctx context.Context, id string, isHandled bool) error) *MockRepository_SetHandledLocally_Call {
	_c.Call.Return(run)
	return _c
}

// SetPriority provides a mock function for the type MockRepository
func (_mock *MockRepository) SetPriority(ctx context.Context, id string, priority int) error {
	ret := _mock.Called(ctx, id, priority)

	if len(ret) == 0 {
		panic("no return value specified for SetPriority")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, id, priority)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPriority'
type MockRepository_SetPriority_Call struct {
	*mock.Call
}

// SetPriority is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - priority int
func (_e *MockRepository_Expecter) SetPriority(ctx any, id any, priority any) *MockRepository_SetPriority_Call {
	return &MockRepository_SetPriority_Call{Call: _e.mock.On("SetPriority", ctx, id, priority)}
}

func (_c *MockRepository_SetPriority_Call) Run(run func(ctx context.Context, id string, priority int)) *MockRepository_SetPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetPriority_Call) Return(err error) *MockRepository_SetPriority_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetPriority_Call) RunAndReturn(run func(ctx context.Context, id string, priority int) error) *MockRepository_SetPriority_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadLocally provides a mock function for the type MockRepository
func (_mock *MockRepository) SetReadLocally(ctx context.Context, id string, isRead bool) error {
	ret := _mock.Called(ctx, id, isRead)

	if len(ret) == 0 {
		panic("no return value specified for SetReadLocally")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isRead)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetReadLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadLocally'
type MockRepository_SetReadLocally_Call struct {
	*mock.Call
}

// SetReadLocally is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isRead bool
func (_e *MockRepository_Expecter) SetReadLocally(ctx any, id any, isRead any) *MockRepository_SetReadLocally_Call {
	return &MockRepository_SetReadLocally_Call{Call: _e.mock.On("SetReadLocally", ctx, id, isRead)}
}

func (_c *MockRepository_SetReadLocally_Call) Run(run func(ctx context.Context, id string, isRead bool)) *MockRepository_SetReadLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetReadLocally_Call) Return(err error) *MockRepository_SetReadLocally_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetReadLocally_Call) RunAndReturn(run func(ctx context.Context, id string, isRead bool) error) *MockRepository_SetReadLocally_Call {
	_c.Call.Return(run)
	return _c
}

// UnarchiveThread provides a mock function for the type MockRepository
func (_mock *MockRepository) UnarchiveThread(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnarchiveThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UnarchiveThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnarchiveThread'
type MockRepository_UnarchiveThread_Call struct {
	*mock.Call
}

// UnarchiveThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) UnarchiveThread(ctx any, id any) *MockRepository_UnarchiveThread_Call {
	return &MockRepository_UnarchiveThread_Call{Call: _e.mock.On("UnarchiveThread", ctx, id)}
}

func (_c *MockRepository_UnarchiveThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_UnarchiveThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UnarchiveThread_Call) Return(err error) *MockRepository_UnarchiveThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UnarchiveThread_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_UnarchiveThread_Call {
	_c.Call.Return(run)
	return _c
}

// UnmuteThread provides a mock function for the type MockRepository
func (_mock *MockRepository) UnmuteThread(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnmuteThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UnmuteThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmuteThread'
type MockRepository_UnmuteThread_Call struct {
	*mock.Call
}

// UnmuteThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) UnmuteThread(ctx any, id any) *MockRepository_UnmuteThread_Call {
	return &MockRepository_UnmuteThread_Call{Call: _e.mock.On("UnmuteThread", ctx, id)}
}

func (_c *MockRepository_UnmuteThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_UnmuteThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UnmuteThread_Call) Return(err error) *MockRepository_UnmuteThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UnmuteThread_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_UnmuteThread_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBridgeHealth provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateBridgeHealth(ctx context.Context, h models.BridgeHealth) error {
	ret := _mock.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BridgeHealth) error); ok {
		r0 = returnFunc(ctx, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBridgeHealth'
type MockRepository_UpdateBridgeHealth_Call struct {
	*mock.Call
}

// UpdateBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - h models.BridgeHealth
func (_e *MockRepository_Expecter) UpdateBridgeHealth(ctx any, h any) *MockRepository_UpdateBridgeHealth_Call {
	return &MockRepository_UpdateBridgeHealth_Call{Call: _e.mock.On("UpdateBridgeHealth", ctx, h)}
}

func (_c *MockRepository_UpdateBridgeHealth_Call) Run(run func(ctx context.Context, h models.BridgeHealth)) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BridgeHealth
		if args[1] != nil {
			arg1 = args[1].(models.BridgeHealth)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateBridgeHealth_Call) Return(err error) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateBridgeHealth_Call) RunAndReturn(run func(ctx context.Context, h models.BridgeHealth) error) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceStateByNodeID provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateResourceStateByNodeID(ctx context.Context, nodeID string, state string, resourceSubState string) error {
	ret := _mock.Called(ctx, nodeID, state, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceStateByNodeID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, nodeID, state, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateResourceStateByNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceStateByNodeID'
type MockRepository_UpdateResourceStateByNodeID_Call struct {
	*mock.Call
}

// UpdateResourceStateByNodeID is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
//   - state string
//   - resourceSubState string
func (_e *MockRepository_Expecter) UpdateResourceStateByNodeID(ctx any, nodeID any, state any, resourceSubState any) *MockRepository_UpdateResourceStateByNodeID_Call {
	return &MockRepository_UpdateResourceStateByNodeID_Call{Call: _e.mock.On("UpdateResourceStateByNodeID", ctx, nodeID, state, resourceSubState)}
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) Run(run func(ctx context.Context, nodeID string, state string, resourceSubState string)) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) Return(err error) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) RunAndReturn(run func(ctx context.Context, nodeID string, state string, resourceSubState string) error) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncMeta provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateSyncMeta(ctx context.Context, s models.SyncMeta) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncMeta")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SyncMeta) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncMeta'
type MockRepository_UpdateSyncMeta_Call struct {
	*mock.Call
}

// UpdateSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - s models.SyncMeta
func (_e *MockRepository_Expecter) UpdateSyncMeta(ctx any, s any) *MockRepository_UpdateSyncMeta_Call {
	return &MockRepository_UpdateSyncMeta_Call{Call: _e.mock.On("UpdateSyncMeta", ctx, s)}
}

func (_c *MockRepository_UpdateSyncMeta_Call) Run(run func(ctx context.Context, s models.SyncMeta)) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SyncMeta
		if args[1] != nil {
			arg1 = args[1].(models.SyncMeta)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateSyncMeta_Call) Return(err error) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateSyncMeta_Call) RunAndReturn(run func(ctx context.Context, s models.SyncMeta) error) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNotifications provides a mock function for the type MockRepository
func (_mock *MockRepository) UpsertNotifications(ctx context.Context, notifications []triage.Notification) error {
	ret := _mock.Called(ctx, notifications)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNotifications")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []triage.Notification) error); ok {
		r0 = returnFunc(ctx, notifications)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpsertNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNotifications'
type MockRepository_UpsertNotifications_Call struct {
	*mock.Call
}

// UpsertNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []triage.Notification
func (_e *MockRepository_Expecter) UpsertNotifications(ctx any, notifications any) *MockRepository_UpsertNotifications_Call {
	return &MockRepository_UpsertNotifications_Call{Call: _e.mock.On("UpsertNotifications", ctx, notifications)}
}

func (_c *MockRepository_UpsertNotifications_Call) Run(run func(ctx context.Context, notifications []triage.Notification)) *MockRepository_UpsertNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []triage.Notification
		if args[1] != nil {
			arg1 = args[1].([]triage.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpsertNotifications_Call) Return(err error) *MockRepository_UpsertNotifications_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpsertNotifications_Call) RunAndReturn(run func(ctx context.Context, notifications []triage.Notification) error) *MockRepository_UpsertNotifications_Call {
	_c.Call.Return(run)
	return _c
}
