// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	github "github.com/hirakiuc/gh-orbit/internal/github"

	mock "github.com/stretchr/testify/mock"

	models "github.com/hirakiuc/gh-orbit/internal/models"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BaseURL provides a mock function with no fields
func (_m *MockClient) BaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockClient_BaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseURL'
type MockClient_BaseURL_Call struct {
	*mock.Call
}

// BaseURL is a helper method to define mock.On call
func (_e *MockClient_Expecter) BaseURL() *MockClient_BaseURL_Call {
	return &MockClient_BaseURL_Call{Call: _e.mock.On("BaseURL")}
}

func (_c *MockClient_BaseURL_Call) Run(run func()) *MockClient_BaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_BaseURL_Call) Return(_a0 string) *MockClient_BaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BaseURL_Call) RunAndReturn(run func() string) *MockClient_BaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function with given fields: ctx
func (_m *MockClient) CurrentUser(ctx context.Context) (*github.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *github.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*github.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *github.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type MockClient_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) CurrentUser(ctx interface{}) *MockClient_CurrentUser_Call {
	return &MockClient_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *MockClient_CurrentUser_Call) Run(run func(ctx context.Context)) *MockClient_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_CurrentUser_Call) Return(_a0 *github.User, _a1 error) *MockClient_CurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CurrentUser_Call) RunAndReturn(run func(context.Context) (*github.User, error)) *MockClient_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// GQL provides a mock function with no fields
func (_m *MockClient) GQL() github.GraphQLClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GQL")
	}

	var r0 github.GraphQLClient
	if rf, ok := ret.Get(0).(func() github.GraphQLClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.GraphQLClient)
		}
	}

	return r0
}

// MockClient_GQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GQL'
type MockClient_GQL_Call struct {
	*mock.Call
}

// GQL is a helper method to define mock.On call
func (_e *MockClient_Expecter) GQL() *MockClient_GQL_Call {
	return &MockClient_GQL_Call{Call: _e.mock.On("GQL")}
}

func (_c *MockClient_GQL_Call) Run(run func()) *MockClient_GQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GQL_Call) Return(_a0 github.GraphQLClient) *MockClient_GQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_GQL_Call) RunAndReturn(run func() github.GraphQLClient) *MockClient_GQL_Call {
	_c.Call.Return(run)
	return _c
}

// HTTP provides a mock function with no fields
func (_m *MockClient) HTTP() *http.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTP")
	}

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

// MockClient_HTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTP'
type MockClient_HTTP_Call struct {
	*mock.Call
}

// HTTP is a helper method to define mock.On call
func (_e *MockClient_Expecter) HTTP() *MockClient_HTTP_Call {
	return &MockClient_HTTP_Call{Call: _e.mock.On("HTTP")}
}

func (_c *MockClient_HTTP_Call) Run(run func()) *MockClient_HTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_HTTP_Call) Return(_a0 *http.Client) *MockClient_HTTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_HTTP_Call) RunAndReturn(run func() *http.Client) *MockClient_HTTP_Call {
	_c.Call.Return(run)
	return _c
}

// MarkThreadAsRead provides a mock function with given fields: ctx, threadID
func (_m *MockClient) MarkThreadAsRead(ctx context.Context, threadID string) error {
	ret := _m.Called(ctx, threadID)

	if len(ret) == 0 {
		panic("no return value specified for MarkThreadAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_MarkThreadAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkThreadAsRead'
type MockClient_MarkThreadAsRead_Call struct {
	*mock.Call
}

// MarkThreadAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - threadID string
func (_e *MockClient_Expecter) MarkThreadAsRead(ctx interface{}, threadID interface{}) *MockClient_MarkThreadAsRead_Call {
	return &MockClient_MarkThreadAsRead_Call{Call: _e.mock.On("MarkThreadAsRead", ctx, threadID)}
}

func (_c *MockClient_MarkThreadAsRead_Call) Run(run func(ctx context.Context, threadID string)) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_MarkThreadAsRead_Call) Return(_a0 error) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_MarkThreadAsRead_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// REST provides a mock function with no fields
func (_m *MockClient) REST() github.RESTClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for REST")
	}

	var r0 github.RESTClient
	if rf, ok := ret.Get(0).(func() github.RESTClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.RESTClient)
		}
	}

	return r0
}

// MockClient_REST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'REST'
type MockClient_REST_Call struct {
	*mock.Call
}

// REST is a helper method to define mock.On call
func (_e *MockClient_Expecter) REST() *MockClient_REST_Call {
	return &MockClient_REST_Call{Call: _e.mock.On("REST")}
}

func (_c *MockClient_REST_Call) Run(run func()) *MockClient_REST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_REST_Call) Return(_a0 github.RESTClient) *MockClient_REST_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_REST_Call) RunAndReturn(run func() github.RESTClient) *MockClient_REST_Call {
	_c.Call.Return(run)
	return _c
}

// ReportRateLimit provides a mock function with given fields: info
func (_m *MockClient) ReportRateLimit(info models.RateLimitInfo) {
	_m.Called(info)
}

// MockClient_ReportRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportRateLimit'
type MockClient_ReportRateLimit_Call struct {
	*mock.Call
}

// ReportRateLimit is a helper method to define mock.On call
//   - info models.RateLimitInfo
func (_e *MockClient_Expecter) ReportRateLimit(info interface{}) *MockClient_ReportRateLimit_Call {
	return &MockClient_ReportRateLimit_Call{Call: _e.mock.On("ReportRateLimit", info)}
}

func (_c *MockClient_ReportRateLimit_Call) Run(run func(info models.RateLimitInfo)) *MockClient_ReportRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.RateLimitInfo))
	})
	return _c
}

func (_c *MockClient_ReportRateLimit_Call) Return() *MockClient_ReportRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_ReportRateLimit_Call) RunAndReturn(run func(models.RateLimitInfo)) *MockClient_ReportRateLimit_Call {
	_c.Run(run)
	return _c
}

// SetRateLimitUpdates provides a mock function with given fields: ch
func (_m *MockClient) SetRateLimitUpdates(ch chan models.RateLimitInfo) {
	_m.Called(ch)
}

// MockClient_SetRateLimitUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRateLimitUpdates'
type MockClient_SetRateLimitUpdates_Call struct {
	*mock.Call
}

// SetRateLimitUpdates is a helper method to define mock.On call
//   - ch chan models.RateLimitInfo
func (_e *MockClient_Expecter) SetRateLimitUpdates(ch interface{}) *MockClient_SetRateLimitUpdates_Call {
	return &MockClient_SetRateLimitUpdates_Call{Call: _e.mock.On("SetRateLimitUpdates", ch)}
}

func (_c *MockClient_SetRateLimitUpdates_Call) Run(run func(ch chan models.RateLimitInfo)) *MockClient_SetRateLimitUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan models.RateLimitInfo))
	})
	return _c
}

func (_c *MockClient_SetRateLimitUpdates_Call) Return() *MockClient_SetRateLimitUpdates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetRateLimitUpdates_Call) RunAndReturn(run func(chan models.RateLimitInfo)) *MockClient_SetRateLimitUpdates_Call {
	_c.Run(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
