// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/models"
	"github.com/hirakiuc/gh-orbit/internal/triage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAlertRepository creates a new instance of MockAlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertRepository {
	mock := &MockAlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlertRepository is an autogenerated mock type for the AlertRepository type
type MockAlertRepository struct {
	mock.Mock
}

type MockAlertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertRepository) EXPECT() *MockAlertRepository_Expecter {
	return &MockAlertRepository_Expecter{mock: &_m.Mock}
}

// GetBridgeHealth provides a mock function for the type MockAlertRepository
func (_mock *MockAlertRepository) GetBridgeHealth(ctx context.Context) (*models.BridgeHealth, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *models.BridgeHealth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.BridgeHealth, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.BridgeHealth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BridgeHealth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlertRepository_GetBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeHealth'
type MockAlertRepository_GetBridgeHealth_Call struct {
	*mock.Call
}

// GetBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRepository_Expecter) GetBridgeHealth(ctx any) *MockAlertRepository_GetBridgeHealth_Call {
	return &MockAlertRepository_GetBridgeHealth_Call{Call: _e.mock.On("GetBridgeHealth", ctx)}
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Run(run func(ctx context.Context)) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Return(bridgeHealth *models.BridgeHealth, err error) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(bridgeHealth, err)
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) RunAndReturn(run func(ctx context.Context) (*models.BridgeHealth, error)) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function for the type MockAlertRepository
func (_mock *MockAlertRepository) ListNotifications(ctx context.Context) ([]triage.NotificationWithState, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []triage.NotificationWithState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]triage.NotificationWithState, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []triage.NotificationWithState); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]triage.NotificationWithState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlertRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockAlertRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRepository_Expecter) ListNotifications(ctx any) *MockAlertRepository_ListNotifications_Call {
	return &MockAlertRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx)}
}

func (_c *MockAlertRepository_ListNotifications_Call) Run(run func(ctx context.Context)) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) Return(notificationWithStates []triage.NotificationWithState, err error) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(notificationWithStates, err)
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) RunAndReturn(run func(ctx context.Context) ([]triage.NotificationWithState, error)) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBridgeHealth provides a mock function for the type MockAlertRepository
func (_mock *MockAlertRepository) UpdateBridgeHealth(ctx context.Context, h models.BridgeHealth) error {
	ret := _mock.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BridgeHealth) error); ok {
		r0 = returnFunc(ctx, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAlertRepository_UpdateBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBridgeHealth'
type MockAlertRepository_UpdateBridgeHealth_Call struct {
	*mock.Call
}

// UpdateBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - h models.BridgeHealth
func (_e *MockAlertRepository_Expecter) UpdateBridgeHealth(ctx any, h any) *MockAlertRepository_UpdateBridgeHealth_Call {
	return &MockAlertRepository_UpdateBridgeHealth_Call{Call: _e.mock.On("UpdateBridgeHealth", ctx, h)}
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Run(run func(ctx context.Context, h models.BridgeHealth)) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BridgeHealth
		if args[1] != nil {
			arg1 = args[1].(models.BridgeHealth)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Return(err error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) RunAndReturn(run func(ctx context.Context, h models.BridgeHealth) error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}
