// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/hirakiuc/gh-orbit/internal/models"
	mock "github.com/stretchr/testify/mock"

	triage "github.com/hirakiuc/gh-orbit/internal/triage"
)

// MockEnricher is an autogenerated mock type for the Enricher type
type MockEnricher struct {
	mock.Mock
}

type MockEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnricher) EXPECT() *MockEnricher_Expecter {
	return &MockEnricher_Expecter{mock: &_m.Mock}
}

// FetchDetail provides a mock function with given fields: ctx, u, subjectType, force
func (_m *MockEnricher) FetchDetail(ctx context.Context, u string, subjectType string, force bool) (models.EnrichmentResult, error) {
	ret := _m.Called(ctx, u, subjectType, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchDetail")
	}

	var r0 models.EnrichmentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (models.EnrichmentResult, error)); ok {
		return rf(ctx, u, subjectType, force)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) models.EnrichmentResult); ok {
		r0 = rf(ctx, u, subjectType, force)
	} else {
		r0 = ret.Get(0).(models.EnrichmentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, u, subjectType, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnricher_FetchDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDetail'
type MockEnricher_FetchDetail_Call struct {
	*mock.Call
}

// FetchDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - u string
//   - subjectType string
//   - force bool
func (_e *MockEnricher_Expecter) FetchDetail(ctx interface{}, u interface{}, subjectType interface{}, force interface{}) *MockEnricher_FetchDetail_Call {
	return &MockEnricher_FetchDetail_Call{Call: _e.mock.On("FetchDetail", ctx, u, subjectType, force)}
}

func (_c *MockEnricher_FetchDetail_Call) Run(run func(ctx context.Context, u string, subjectType string, force bool)) *MockEnricher_FetchDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) Return(_a0 models.EnrichmentResult, _a1 error) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) RunAndReturn(run func(context.Context, string, string, bool) (models.EnrichmentResult, error)) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHybridBatch provides a mock function with given fields: ctx, notifications, force
func (_m *MockEnricher) FetchHybridBatch(ctx context.Context, notifications []triage.NotificationWithState, force bool) map[string]models.EnrichmentResult {
	ret := _m.Called(ctx, notifications, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchHybridBatch")
	}

	var r0 map[string]models.EnrichmentResult
	if rf, ok := ret.Get(0).(func(context.Context, []triage.NotificationWithState, bool) map[string]models.EnrichmentResult); ok {
		r0 = rf(ctx, notifications, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.EnrichmentResult)
		}
	}

	return r0
}

// MockEnricher_FetchHybridBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHybridBatch'
type MockEnricher_FetchHybridBatch_Call struct {
	*mock.Call
}

// FetchHybridBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []triage.NotificationWithState
//   - force bool
func (_e *MockEnricher_Expecter) FetchHybridBatch(ctx interface{}, notifications interface{}, force interface{}) *MockEnricher_FetchHybridBatch_Call {
	return &MockEnricher_FetchHybridBatch_Call{Call: _e.mock.On("FetchHybridBatch", ctx, notifications, force)}
}

func (_c *MockEnricher_FetchHybridBatch_Call) Run(run func(ctx context.Context, notifications []triage.NotificationWithState, force bool)) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]triage.NotificationWithState), args[2].(bool))
	})
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) Return(_a0 map[string]models.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) RunAndReturn(run func(context.Context, []triage.NotificationWithState, bool) map[string]models.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockEnricher) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// MockEnricher_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockEnricher_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEnricher_Expecter) Shutdown(ctx interface{}) *MockEnricher_Shutdown_Call {
	return &MockEnricher_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockEnricher_Shutdown_Call) Run(run func(ctx context.Context)) *MockEnricher_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEnricher_Shutdown_Call) Return() *MockEnricher_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnricher_Shutdown_Call) RunAndReturn(run func(context.Context)) *MockEnricher_Shutdown_Call {
	_c.Run(run)
	return _c
}

// NewMockEnricher creates a new instance of MockEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnricher {
	mock := &MockEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
