// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	db "github.com/hirakiuc/gh-orbit/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// MockSyncRepository is an autogenerated mock type for the SyncRepository type
type MockSyncRepository struct {
	mock.Mock
}

type MockSyncRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncRepository) EXPECT() *MockSyncRepository_Expecter {
	return &MockSyncRepository_Expecter{mock: &_m.Mock}
}

// GetNotification provides a mock function with given fields: id
func (_m *MockSyncRepository) GetNotification(id string) (*db.NotificationWithState, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NotificationWithState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NotificationWithState); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockSyncRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - id string
func (_e *MockSyncRepository_Expecter) GetNotification(id interface{}) *MockSyncRepository_GetNotification_Call {
	return &MockSyncRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", id)}
}

func (_c *MockSyncRepository_GetNotification_Call) Run(run func(id string)) *MockSyncRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSyncRepository_GetNotification_Call) Return(_a0 *db.NotificationWithState, _a1 error) *MockSyncRepository_GetNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncRepository_GetNotification_Call) RunAndReturn(run func(string) (*db.NotificationWithState, error)) *MockSyncRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncMeta provides a mock function with given fields: userID, key
func (_m *MockSyncRepository) GetSyncMeta(userID string, key string) (*db.SyncMeta, error) {
	ret := _m.Called(userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncMeta")
	}

	var r0 *db.SyncMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*db.SyncMeta, error)); ok {
		return rf(userID, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) *db.SyncMeta); ok {
		r0 = rf(userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncRepository_GetSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncMeta'
type MockSyncRepository_GetSyncMeta_Call struct {
	*mock.Call
}

// GetSyncMeta is a helper method to define mock.On call
//   - userID string
//   - key string
func (_e *MockSyncRepository_Expecter) GetSyncMeta(userID interface{}, key interface{}) *MockSyncRepository_GetSyncMeta_Call {
	return &MockSyncRepository_GetSyncMeta_Call{Call: _e.mock.On("GetSyncMeta", userID, key)}
}

func (_c *MockSyncRepository_GetSyncMeta_Call) Run(run func(userID string, key string)) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSyncRepository_GetSyncMeta_Call) Return(_a0 *db.SyncMeta, _a1 error) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncRepository_GetSyncMeta_Call) RunAndReturn(run func(string, string) (*db.SyncMeta, error)) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotifiedBatch provides a mock function with given fields: ids
func (_m *MockSyncRepository) MarkNotifiedBatch(ids []string) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotifiedBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_MarkNotifiedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotifiedBatch'
type MockSyncRepository_MarkNotifiedBatch_Call struct {
	*mock.Call
}

// MarkNotifiedBatch is a helper method to define mock.On call
//   - ids []string
func (_e *MockSyncRepository_Expecter) MarkNotifiedBatch(ids interface{}) *MockSyncRepository_MarkNotifiedBatch_Call {
	return &MockSyncRepository_MarkNotifiedBatch_Call{Call: _e.mock.On("MarkNotifiedBatch", ids)}
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) Run(run func(ids []string)) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) Return(_a0 error) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) RunAndReturn(run func([]string) error) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncMeta provides a mock function with given fields: s
func (_m *MockSyncRepository) UpdateSyncMeta(s db.SyncMeta) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.SyncMeta) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_UpdateSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncMeta'
type MockSyncRepository_UpdateSyncMeta_Call struct {
	*mock.Call
}

// UpdateSyncMeta is a helper method to define mock.On call
//   - s db.SyncMeta
func (_e *MockSyncRepository_Expecter) UpdateSyncMeta(s interface{}) *MockSyncRepository_UpdateSyncMeta_Call {
	return &MockSyncRepository_UpdateSyncMeta_Call{Call: _e.mock.On("UpdateSyncMeta", s)}
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) Run(run func(s db.SyncMeta)) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.SyncMeta))
	})
	return _c
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) Return(_a0 error) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) RunAndReturn(run func(db.SyncMeta) error) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNotification provides a mock function with given fields: n
func (_m *MockSyncRepository) UpsertNotification(n db.Notification) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Notification) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_UpsertNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNotification'
type MockSyncRepository_UpsertNotification_Call struct {
	*mock.Call
}

// UpsertNotification is a helper method to define mock.On call
//   - n db.Notification
func (_e *MockSyncRepository_Expecter) UpsertNotification(n interface{}) *MockSyncRepository_UpsertNotification_Call {
	return &MockSyncRepository_UpsertNotification_Call{Call: _e.mock.On("UpsertNotification", n)}
}

func (_c *MockSyncRepository_UpsertNotification_Call) Run(run func(n db.Notification)) *MockSyncRepository_UpsertNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.Notification))
	})
	return _c
}

func (_c *MockSyncRepository_UpsertNotification_Call) Return(_a0 error) *MockSyncRepository_UpsertNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_UpsertNotification_Call) RunAndReturn(run func(db.Notification) error) *MockSyncRepository_UpsertNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncRepository creates a new instance of MockSyncRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncRepository {
	mock := &MockSyncRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
