// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEnrichmentRepository is an autogenerated mock type for the EnrichmentRepository type
type MockEnrichmentRepository struct {
	mock.Mock
}

type MockEnrichmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrichmentRepository) EXPECT() *MockEnrichmentRepository_Expecter {
	return &MockEnrichmentRepository_Expecter{mock: &_m.Mock}
}

// EnrichNotification provides a mock function with given fields: ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState
func (_m *MockEnrichmentRepository) EnrichNotification(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error {
	ret := _m.Called(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for EnrichNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnrichmentRepository_EnrichNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichNotification'
type MockEnrichmentRepository_EnrichNotification_Call struct {
	*mock.Call
}

// EnrichNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - nodeID string
//   - body string
//   - author string
//   - htmlURL string
//   - resourceState string
//   - resourceSubState string
func (_e *MockEnrichmentRepository_Expecter) EnrichNotification(ctx interface{}, id interface{}, nodeID interface{}, body interface{}, author interface{}, htmlURL interface{}, resourceState interface{}, resourceSubState interface{}) *MockEnrichmentRepository_EnrichNotification_Call {
	return &MockEnrichmentRepository_EnrichNotification_Call{Call: _e.mock.On("EnrichNotification", ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)}
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) Run(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string)) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(string))
	})
	return _c
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) Return(_a0 error) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string, string) error) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceStateByNodeID provides a mock function with given fields: ctx, nodeID, state, resourceSubState
func (_m *MockEnrichmentRepository) UpdateResourceStateByNodeID(ctx context.Context, nodeID string, state string, resourceSubState string) error {
	ret := _m.Called(ctx, nodeID, state, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceStateByNodeID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, nodeID, state, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnrichmentRepository_UpdateResourceStateByNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceStateByNodeID'
type MockEnrichmentRepository_UpdateResourceStateByNodeID_Call struct {
	*mock.Call
}

// UpdateResourceStateByNodeID is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
//   - state string
//   - resourceSubState string
func (_e *MockEnrichmentRepository_Expecter) UpdateResourceStateByNodeID(ctx interface{}, nodeID interface{}, state interface{}, resourceSubState interface{}) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	return &MockEnrichmentRepository_UpdateResourceStateByNodeID_Call{Call: _e.mock.On("UpdateResourceStateByNodeID", ctx, nodeID, state, resourceSubState)}
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) Run(run func(ctx context.Context, nodeID string, state string, resourceSubState string)) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) Return(_a0 error) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnrichmentRepository creates a new instance of MockEnrichmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrichmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrichmentRepository {
	mock := &MockEnrichmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
