// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/models"
	"github.com/hirakiuc/gh-orbit/internal/triage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEnricher creates a new instance of MockEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnricher {
	mock := &MockEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnricher is an autogenerated mock type for the Enricher type
type MockEnricher struct {
	mock.Mock
}

type MockEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnricher) EXPECT() *MockEnricher_Expecter {
	return &MockEnricher_Expecter{mock: &_m.Mock}
}

// FetchDetail provides a mock function for the type MockEnricher
func (_mock *MockEnricher) FetchDetail(ctx context.Context, u string, subjectType string, force bool) (models.EnrichmentResult, error) {
	ret := _mock.Called(ctx, u, subjectType, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchDetail")
	}

	var r0 models.EnrichmentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (models.EnrichmentResult, error)); ok {
		return returnFunc(ctx, u, subjectType, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) models.EnrichmentResult); ok {
		r0 = returnFunc(ctx, u, subjectType, force)
	} else {
		r0 = ret.Get(0).(models.EnrichmentResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, u, subjectType, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnricher_FetchDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDetail'
type MockEnricher_FetchDetail_Call struct {
	*mock.Call
}

// FetchDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - u string
//   - subjectType string
//   - force bool
func (_e *MockEnricher_Expecter) FetchDetail(ctx interface{}, u interface{}, subjectType interface{}, force interface{}) *MockEnricher_FetchDetail_Call {
	return &MockEnricher_FetchDetail_Call{Call: _e.mock.On("FetchDetail", ctx, u, subjectType, force)}
}

func (_c *MockEnricher_FetchDetail_Call) Run(run func(ctx context.Context, u string, subjectType string, force bool)) *MockEnricher_FetchDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) Return(enrichmentResult models.EnrichmentResult, err error) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(enrichmentResult, err)
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) RunAndReturn(run func(ctx context.Context, u string, subjectType string, force bool) (models.EnrichmentResult, error)) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHybridBatch provides a mock function for the type MockEnricher
func (_mock *MockEnricher) FetchHybridBatch(ctx context.Context, notifications []triage.NotificationWithState, force bool) map[string]models.EnrichmentResult {
	ret := _mock.Called(ctx, notifications, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchHybridBatch")
	}

	var r0 map[string]models.EnrichmentResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, []triage.NotificationWithState, bool) map[string]models.EnrichmentResult); ok {
		r0 = returnFunc(ctx, notifications, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.EnrichmentResult)
		}
	}
	return r0
}

// MockEnricher_FetchHybridBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHybridBatch'
type MockEnricher_FetchHybridBatch_Call struct {
	*mock.Call
}

// FetchHybridBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []triage.NotificationWithState
//   - force bool
func (_e *MockEnricher_Expecter) FetchHybridBatch(ctx interface{}, notifications interface{}, force interface{}) *MockEnricher_FetchHybridBatch_Call {
	return &MockEnricher_FetchHybridBatch_Call{Call: _e.mock.On("FetchHybridBatch", ctx, notifications, force)}
}

func (_c *MockEnricher_FetchHybridBatch_Call) Run(run func(ctx context.Context, notifications []triage.NotificationWithState, force bool)) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []triage.NotificationWithState
		if args[1] != nil {
			arg1 = args[1].([]triage.NotificationWithState)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) Return(stringToEnrichmentResult map[string]models.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(stringToEnrichmentResult)
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) RunAndReturn(run func(ctx context.Context, notifications []triage.NotificationWithState, force bool) map[string]models.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(run)
	return _c
}

// PersistFetchedDetail provides a mock function for the type MockEnricher
func (_mock *MockEnricher) PersistFetchedDetail(ctx context.Context, id string, sourceURL string, res models.EnrichmentResult) error {
	ret := _mock.Called(ctx, id, sourceURL, res)

	if len(ret) == 0 {
		panic("no return value specified for PersistFetchedDetail")
	}

	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, models.EnrichmentResult) error); ok {
		return returnFunc(ctx, id, sourceURL, res)
	}

	return ret.Error(0)
}

// MockEnricher_PersistFetchedDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistFetchedDetail'
type MockEnricher_PersistFetchedDetail_Call struct {
	*mock.Call
}

// PersistFetchedDetail is a helper method to define mock.On call
func (_e *MockEnricher_Expecter) PersistFetchedDetail(ctx interface{}, id interface{}, sourceURL interface{}, res interface{}) *MockEnricher_PersistFetchedDetail_Call {
	return &MockEnricher_PersistFetchedDetail_Call{Call: _e.mock.On("PersistFetchedDetail", ctx, id, sourceURL, res)}
}

func (_c *MockEnricher_PersistFetchedDetail_Call) Run(run func(ctx context.Context, id string, sourceURL string, res models.EnrichmentResult)) *MockEnricher_PersistFetchedDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 models.EnrichmentResult
		if args[3] != nil {
			arg3 = args[3].(models.EnrichmentResult)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockEnricher_PersistFetchedDetail_Call) Return(err error) *MockEnricher_PersistFetchedDetail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnricher_PersistFetchedDetail_Call) RunAndReturn(run func(ctx context.Context, id string, sourceURL string, res models.EnrichmentResult) error) *MockEnricher_PersistFetchedDetail_Call {
	_c.Call.Return(run)
	return _c
}

// PersistIndependentDetail provides a mock function for the type MockEnricher
func (_mock *MockEnricher) PersistIndependentDetail(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error {
	ret := _mock.Called(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for PersistIndependentDetail")
	}

	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		return returnFunc(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)
	}

	return ret.Error(0)
}

// MockEnricher_PersistIndependentDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistIndependentDetail'
type MockEnricher_PersistIndependentDetail_Call struct {
	*mock.Call
}

// PersistIndependentDetail is a helper method to define mock.On call
func (_e *MockEnricher_Expecter) PersistIndependentDetail(ctx interface{}, id interface{}, nodeID interface{}, body interface{}, author interface{}, htmlURL interface{}, resourceState interface{}, resourceSubState interface{}) *MockEnricher_PersistIndependentDetail_Call {
	return &MockEnricher_PersistIndependentDetail_Call{Call: _e.mock.On("PersistIndependentDetail", ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)}
}

func (_c *MockEnricher_PersistIndependentDetail_Call) Run(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string)) *MockEnricher_PersistIndependentDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		run(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	})
	return _c
}

func (_c *MockEnricher_PersistIndependentDetail_Call) Return(err error) *MockEnricher_PersistIndependentDetail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnricher_PersistIndependentDetail_Call) RunAndReturn(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error) *MockEnricher_PersistIndependentDetail_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockEnricher
func (_mock *MockEnricher) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockEnricher_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockEnricher_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEnricher_Expecter) Shutdown(ctx interface{}) *MockEnricher_Shutdown_Call {
	return &MockEnricher_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockEnricher_Shutdown_Call) Run(run func(ctx context.Context)) *MockEnricher_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnricher_Shutdown_Call) Return() *MockEnricher_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnricher_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockEnricher_Shutdown_Call {
	_c.Run(run)
	return _c
}
