// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	types "github.com/hirakiuc/gh-orbit/internal/types"
)

// MockGitHubClient is an autogenerated mock type for the GitHubClient type
type MockGitHubClient struct {
	mock.Mock
}

type MockGitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitHubClient) EXPECT() *MockGitHubClient_Expecter {
	return &MockGitHubClient_Expecter{mock: &_m.Mock}
}

// BaseURL provides a mock function with no fields
func (_m *MockGitHubClient) BaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitHubClient_BaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseURL'
type MockGitHubClient_BaseURL_Call struct {
	*mock.Call
}

// BaseURL is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) BaseURL() *MockGitHubClient_BaseURL_Call {
	return &MockGitHubClient_BaseURL_Call{Call: _e.mock.On("BaseURL")}
}

func (_c *MockGitHubClient_BaseURL_Call) Run(run func()) *MockGitHubClient_BaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_BaseURL_Call) Return(_a0 string) *MockGitHubClient_BaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_BaseURL_Call) RunAndReturn(run func() string) *MockGitHubClient_BaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function with given fields: ctx
func (_m *MockGitHubClient) CurrentUser(ctx context.Context) (*types.GHUser, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *types.GHUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.GHUser, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.GHUser); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.GHUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubClient_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type MockGitHubClient_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGitHubClient_Expecter) CurrentUser(ctx interface{}) *MockGitHubClient_CurrentUser_Call {
	return &MockGitHubClient_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *MockGitHubClient_CurrentUser_Call) Run(run func(ctx context.Context)) *MockGitHubClient_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGitHubClient_CurrentUser_Call) Return(_a0 *types.GHUser, _a1 error) *MockGitHubClient_CurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubClient_CurrentUser_Call) RunAndReturn(run func(context.Context) (*types.GHUser, error)) *MockGitHubClient_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// GQL provides a mock function with no fields
func (_m *MockGitHubClient) GQL() types.GraphQLClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GQL")
	}

	var r0 types.GraphQLClient
	if rf, ok := ret.Get(0).(func() types.GraphQLClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.GraphQLClient)
		}
	}

	return r0
}

// MockGitHubClient_GQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GQL'
type MockGitHubClient_GQL_Call struct {
	*mock.Call
}

// GQL is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) GQL() *MockGitHubClient_GQL_Call {
	return &MockGitHubClient_GQL_Call{Call: _e.mock.On("GQL")}
}

func (_c *MockGitHubClient_GQL_Call) Run(run func()) *MockGitHubClient_GQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_GQL_Call) Return(_a0 types.GraphQLClient) *MockGitHubClient_GQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_GQL_Call) RunAndReturn(run func() types.GraphQLClient) *MockGitHubClient_GQL_Call {
	_c.Call.Return(run)
	return _c
}

// HTTP provides a mock function with no fields
func (_m *MockGitHubClient) HTTP() *http.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTP")
	}

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

// MockGitHubClient_HTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTP'
type MockGitHubClient_HTTP_Call struct {
	*mock.Call
}

// HTTP is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) HTTP() *MockGitHubClient_HTTP_Call {
	return &MockGitHubClient_HTTP_Call{Call: _e.mock.On("HTTP")}
}

func (_c *MockGitHubClient_HTTP_Call) Run(run func()) *MockGitHubClient_HTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_HTTP_Call) Return(_a0 *http.Client) *MockGitHubClient_HTTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_HTTP_Call) RunAndReturn(run func() *http.Client) *MockGitHubClient_HTTP_Call {
	_c.Call.Return(run)
	return _c
}

// MarkThreadAsRead provides a mock function with given fields: ctx, threadID
func (_m *MockGitHubClient) MarkThreadAsRead(ctx context.Context, threadID string) error {
	ret := _m.Called(ctx, threadID)

	if len(ret) == 0 {
		panic("no return value specified for MarkThreadAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitHubClient_MarkThreadAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkThreadAsRead'
type MockGitHubClient_MarkThreadAsRead_Call struct {
	*mock.Call
}

// MarkThreadAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - threadID string
func (_e *MockGitHubClient_Expecter) MarkThreadAsRead(ctx interface{}, threadID interface{}) *MockGitHubClient_MarkThreadAsRead_Call {
	return &MockGitHubClient_MarkThreadAsRead_Call{Call: _e.mock.On("MarkThreadAsRead", ctx, threadID)}
}

func (_c *MockGitHubClient_MarkThreadAsRead_Call) Run(run func(ctx context.Context, threadID string)) *MockGitHubClient_MarkThreadAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGitHubClient_MarkThreadAsRead_Call) Return(_a0 error) *MockGitHubClient_MarkThreadAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_MarkThreadAsRead_Call) RunAndReturn(run func(context.Context, string) error) *MockGitHubClient_MarkThreadAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// REST provides a mock function with no fields
func (_m *MockGitHubClient) REST() types.RESTClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for REST")
	}

	var r0 types.RESTClient
	if rf, ok := ret.Get(0).(func() types.RESTClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.RESTClient)
		}
	}

	return r0
}

// MockGitHubClient_REST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'REST'
type MockGitHubClient_REST_Call struct {
	*mock.Call
}

// REST is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) REST() *MockGitHubClient_REST_Call {
	return &MockGitHubClient_REST_Call{Call: _e.mock.On("REST")}
}

func (_c *MockGitHubClient_REST_Call) Run(run func()) *MockGitHubClient_REST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_REST_Call) Return(_a0 types.RESTClient) *MockGitHubClient_REST_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_REST_Call) RunAndReturn(run func() types.RESTClient) *MockGitHubClient_REST_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitHubClient creates a new instance of MockGitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitHubClient {
	mock := &MockGitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
