// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRESTClient creates a new instance of MockRESTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRESTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRESTClient {
	mock := &MockRESTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRESTClient is an autogenerated mock type for the RESTClient type
type MockRESTClient struct {
	mock.Mock
}

type MockRESTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRESTClient) EXPECT() *MockRESTClient_Expecter {
	return &MockRESTClient_Expecter{mock: &_m.Mock}
}

// DoWithContext provides a mock function for the type MockRESTClient
func (_mock *MockRESTClient) DoWithContext(ctx context.Context, method string, path string, body io.Reader, response any) error {
	ret := _mock.Called(ctx, method, path, body, response)

	if len(ret) == 0 {
		panic("no return value specified for DoWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, any) error); ok {
		r0 = returnFunc(ctx, method, path, body, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRESTClient_DoWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithContext'
type MockRESTClient_DoWithContext_Call struct {
	*mock.Call
}

// DoWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body io.Reader
//   - response any
func (_e *MockRESTClient_Expecter) DoWithContext(ctx interface{}, method interface{}, path interface{}, body interface{}, response interface{}) *MockRESTClient_DoWithContext_Call {
	return &MockRESTClient_DoWithContext_Call{Call: _e.mock.On("DoWithContext", ctx, method, path, body, response)}
}

func (_c *MockRESTClient_DoWithContext_Call) Run(run func(ctx context.Context, method string, path string, body io.Reader, response any)) *MockRESTClient_DoWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRESTClient_DoWithContext_Call) Return(err error) *MockRESTClient_DoWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRESTClient_DoWithContext_Call) RunAndReturn(run func(ctx context.Context, method string, path string, body io.Reader, response any) error) *MockRESTClient_DoWithContext_Call {
	_c.Call.Return(run)
	return _c
}
