// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/hirakiuc/gh-orbit/internal/models"
	mock "github.com/stretchr/testify/mock"

	triage "github.com/hirakiuc/gh-orbit/internal/triage"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ArchiveThread provides a mock function with given fields: ctx, id
func (_m *MockRepository) ArchiveThread(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ArchiveThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveThread'
type MockRepository_ArchiveThread_Call struct {
	*mock.Call
}

// ArchiveThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) ArchiveThread(ctx interface{}, id interface{}) *MockRepository_ArchiveThread_Call {
	return &MockRepository_ArchiveThread_Call{Call: _e.mock.On("ArchiveThread", ctx, id)}
}

func (_c *MockRepository_ArchiveThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_ArchiveThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ArchiveThread_Call) Return(_a0 error) *MockRepository_ArchiveThread_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ArchiveThread_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_ArchiveThread_Call {
	_c.Call.Return(run)
	return _c
}

// EnrichNotification provides a mock function with given fields: ctx, id, body, author, htmlURL, resourceState
func (_m *MockRepository) EnrichNotification(ctx context.Context, id string, body string, author string, htmlURL string, resourceState string) error {
	ret := _m.Called(ctx, id, body, author, htmlURL, resourceState)

	if len(ret) == 0 {
		panic("no return value specified for EnrichNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, body, author, htmlURL, resourceState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_EnrichNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichNotification'
type MockRepository_EnrichNotification_Call struct {
	*mock.Call
}

// EnrichNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - body string
//   - author string
//   - htmlURL string
//   - resourceState string
func (_e *MockRepository_Expecter) EnrichNotification(ctx interface{}, id interface{}, body interface{}, author interface{}, htmlURL interface{}, resourceState interface{}) *MockRepository_EnrichNotification_Call {
	return &MockRepository_EnrichNotification_Call{Call: _e.mock.On("EnrichNotification", ctx, id, body, author, htmlURL, resourceState)}
}

func (_c *MockRepository_EnrichNotification_Call) Run(run func(ctx context.Context, id string, body string, author string, htmlURL string, resourceState string)) *MockRepository_EnrichNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_EnrichNotification_Call) Return(_a0 error) *MockRepository_EnrichNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_EnrichNotification_Call) RunAndReturn(run func(context.Context, string, string, string, string, string) error) *MockRepository_EnrichNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetBridgeHealth provides a mock function with given fields: ctx
func (_m *MockRepository) GetBridgeHealth(ctx context.Context) (*models.BridgeHealth, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *models.BridgeHealth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.BridgeHealth, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.BridgeHealth); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BridgeHealth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeHealth'
type MockRepository_GetBridgeHealth_Call struct {
	*mock.Call
}

// GetBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetBridgeHealth(ctx interface{}) *MockRepository_GetBridgeHealth_Call {
	return &MockRepository_GetBridgeHealth_Call{Call: _e.mock.On("GetBridgeHealth", ctx)}
}

func (_c *MockRepository_GetBridgeHealth_Call) Run(run func(ctx context.Context)) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetBridgeHealth_Call) Return(_a0 *models.BridgeHealth, _a1 error) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetBridgeHealth_Call) RunAndReturn(run func(context.Context) (*models.BridgeHealth, error)) *MockRepository_GetBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotification provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetNotification(ctx context.Context, id string) (*triage.NotificationWithState, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *triage.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*triage.NotificationWithState, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *triage.NotificationWithState); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*triage.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetNotification(ctx interface{}, id interface{}) *MockRepository_GetNotification_Call {
	return &MockRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", ctx, id)}
}

func (_c *MockRepository_GetNotification_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetNotification_Call) Return(_a0 *triage.NotificationWithState, _a1 error) *MockRepository_GetNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetNotification_Call) RunAndReturn(run func(context.Context, string) (*triage.NotificationWithState, error)) *MockRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncMeta provides a mock function with given fields: ctx, userID, key
func (_m *MockRepository) GetSyncMeta(ctx context.Context, userID string, key string) (*models.SyncMeta, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncMeta")
	}

	var r0 *models.SyncMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.SyncMeta, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.SyncMeta); ok {
		r0 = rf(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SyncMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncMeta'
type MockRepository_GetSyncMeta_Call struct {
	*mock.Call
}

// GetSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *MockRepository_Expecter) GetSyncMeta(ctx interface{}, userID interface{}, key interface{}) *MockRepository_GetSyncMeta_Call {
	return &MockRepository_GetSyncMeta_Call{Call: _e.mock.On("GetSyncMeta", ctx, userID, key)}
}

func (_c *MockRepository_GetSyncMeta_Call) Run(run func(ctx context.Context, userID string, key string)) *MockRepository_GetSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetSyncMeta_Call) Return(_a0 *models.SyncMeta, _a1 error) *MockRepository_GetSyncMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSyncMeta_Call) RunAndReturn(run func(context.Context, string, string) (*models.SyncMeta, error)) *MockRepository_GetSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function with given fields: ctx
func (_m *MockRepository) ListNotifications(ctx context.Context) ([]triage.NotificationWithState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []triage.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]triage.NotificationWithState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []triage.NotificationWithState); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]triage.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListNotifications(ctx interface{}) *MockRepository_ListNotifications_Call {
	return &MockRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx)}
}

func (_c *MockRepository_ListNotifications_Call) Run(run func(ctx context.Context)) *MockRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListNotifications_Call) Return(_a0 []triage.NotificationWithState, _a1 error) *MockRepository_ListNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListNotifications_Call) RunAndReturn(run func(context.Context) ([]triage.NotificationWithState, error)) *MockRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotifiedBatch provides a mock function with given fields: ctx, ids
func (_m *MockRepository) MarkNotifiedBatch(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotifiedBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkNotifiedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotifiedBatch'
type MockRepository_MarkNotifiedBatch_Call struct {
	*mock.Call
}

// MarkNotifiedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) MarkNotifiedBatch(ctx interface{}, ids interface{}) *MockRepository_MarkNotifiedBatch_Call {
	return &MockRepository_MarkNotifiedBatch_Call{Call: _e.mock.On("MarkNotifiedBatch", ctx, ids)}
}

func (_c *MockRepository_MarkNotifiedBatch_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRepository_MarkNotifiedBatch_Call) Return(_a0 error) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkNotifiedBatch_Call) RunAndReturn(run func(context.Context, []string) error) *MockRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReadLocally provides a mock function with given fields: ctx, id, isRead
func (_m *MockRepository) MarkReadLocally(ctx context.Context, id string, isRead bool) error {
	ret := _m.Called(ctx, id, isRead)

	if len(ret) == 0 {
		panic("no return value specified for MarkReadLocally")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, isRead)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkReadLocally_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReadLocally'
type MockRepository_MarkReadLocally_Call struct {
	*mock.Call
}

// MarkReadLocally is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isRead bool
func (_e *MockRepository_Expecter) MarkReadLocally(ctx interface{}, id interface{}, isRead interface{}) *MockRepository_MarkReadLocally_Call {
	return &MockRepository_MarkReadLocally_Call{Call: _e.mock.On("MarkReadLocally", ctx, id, isRead)}
}

func (_c *MockRepository_MarkReadLocally_Call) Run(run func(ctx context.Context, id string, isRead bool)) *MockRepository_MarkReadLocally_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockRepository_MarkReadLocally_Call) Return(_a0 error) *MockRepository_MarkReadLocally_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkReadLocally_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockRepository_MarkReadLocally_Call {
	_c.Call.Return(run)
	return _c
}

// MuteThread provides a mock function with given fields: ctx, id
func (_m *MockRepository) MuteThread(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MuteThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MuteThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MuteThread'
type MockRepository_MuteThread_Call struct {
	*mock.Call
}

// MuteThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) MuteThread(ctx interface{}, id interface{}) *MockRepository_MuteThread_Call {
	return &MockRepository_MuteThread_Call{Call: _e.mock.On("MuteThread", ctx, id)}
}

func (_c *MockRepository_MuteThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_MuteThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_MuteThread_Call) Return(_a0 error) *MockRepository_MuteThread_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MuteThread_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_MuteThread_Call {
	_c.Call.Return(run)
	return _c
}

// SetPriority provides a mock function with given fields: ctx, id, priority
func (_m *MockRepository) SetPriority(ctx context.Context, id string, priority int) error {
	ret := _m.Called(ctx, id, priority)

	if len(ret) == 0 {
		panic("no return value specified for SetPriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, id, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPriority'
type MockRepository_SetPriority_Call struct {
	*mock.Call
}

// SetPriority is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - priority int
func (_e *MockRepository_Expecter) SetPriority(ctx interface{}, id interface{}, priority interface{}) *MockRepository_SetPriority_Call {
	return &MockRepository_SetPriority_Call{Call: _e.mock.On("SetPriority", ctx, id, priority)}
}

func (_c *MockRepository_SetPriority_Call) Run(run func(ctx context.Context, id string, priority int)) *MockRepository_SetPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_SetPriority_Call) Return(_a0 error) *MockRepository_SetPriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetPriority_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRepository_SetPriority_Call {
	_c.Call.Return(run)
	return _c
}

// UnarchiveThread provides a mock function with given fields: ctx, id
func (_m *MockRepository) UnarchiveThread(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnarchiveThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UnarchiveThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnarchiveThread'
type MockRepository_UnarchiveThread_Call struct {
	*mock.Call
}

// UnarchiveThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) UnarchiveThread(ctx interface{}, id interface{}) *MockRepository_UnarchiveThread_Call {
	return &MockRepository_UnarchiveThread_Call{Call: _e.mock.On("UnarchiveThread", ctx, id)}
}

func (_c *MockRepository_UnarchiveThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_UnarchiveThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_UnarchiveThread_Call) Return(_a0 error) *MockRepository_UnarchiveThread_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UnarchiveThread_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_UnarchiveThread_Call {
	_c.Call.Return(run)
	return _c
}

// UnmuteThread provides a mock function with given fields: ctx, id
func (_m *MockRepository) UnmuteThread(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnmuteThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UnmuteThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmuteThread'
type MockRepository_UnmuteThread_Call struct {
	*mock.Call
}

// UnmuteThread is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) UnmuteThread(ctx interface{}, id interface{}) *MockRepository_UnmuteThread_Call {
	return &MockRepository_UnmuteThread_Call{Call: _e.mock.On("UnmuteThread", ctx, id)}
}

func (_c *MockRepository_UnmuteThread_Call) Run(run func(ctx context.Context, id string)) *MockRepository_UnmuteThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_UnmuteThread_Call) Return(_a0 error) *MockRepository_UnmuteThread_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UnmuteThread_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_UnmuteThread_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBridgeHealth provides a mock function with given fields: ctx, h
func (_m *MockRepository) UpdateBridgeHealth(ctx context.Context, h models.BridgeHealth) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.BridgeHealth) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBridgeHealth'
type MockRepository_UpdateBridgeHealth_Call struct {
	*mock.Call
}

// UpdateBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - h models.BridgeHealth
func (_e *MockRepository_Expecter) UpdateBridgeHealth(ctx interface{}, h interface{}) *MockRepository_UpdateBridgeHealth_Call {
	return &MockRepository_UpdateBridgeHealth_Call{Call: _e.mock.On("UpdateBridgeHealth", ctx, h)}
}

func (_c *MockRepository_UpdateBridgeHealth_Call) Run(run func(ctx context.Context, h models.BridgeHealth)) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.BridgeHealth))
	})
	return _c
}

func (_c *MockRepository_UpdateBridgeHealth_Call) Return(_a0 error) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateBridgeHealth_Call) RunAndReturn(run func(context.Context, models.BridgeHealth) error) *MockRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceStateByNodeID provides a mock function with given fields: ctx, nodeID, state
func (_m *MockRepository) UpdateResourceStateByNodeID(ctx context.Context, nodeID string, state string) error {
	ret := _m.Called(ctx, nodeID, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceStateByNodeID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateResourceStateByNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceStateByNodeID'
type MockRepository_UpdateResourceStateByNodeID_Call struct {
	*mock.Call
}

// UpdateResourceStateByNodeID is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
//   - state string
func (_e *MockRepository_Expecter) UpdateResourceStateByNodeID(ctx interface{}, nodeID interface{}, state interface{}) *MockRepository_UpdateResourceStateByNodeID_Call {
	return &MockRepository_UpdateResourceStateByNodeID_Call{Call: _e.mock.On("UpdateResourceStateByNodeID", ctx, nodeID, state)}
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) Run(run func(ctx context.Context, nodeID string, state string)) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) Return(_a0 error) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateResourceStateByNodeID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncMeta provides a mock function with given fields: ctx, s
func (_m *MockRepository) UpdateSyncMeta(ctx context.Context, s models.SyncMeta) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SyncMeta) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncMeta'
type MockRepository_UpdateSyncMeta_Call struct {
	*mock.Call
}

// UpdateSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - s models.SyncMeta
func (_e *MockRepository_Expecter) UpdateSyncMeta(ctx interface{}, s interface{}) *MockRepository_UpdateSyncMeta_Call {
	return &MockRepository_UpdateSyncMeta_Call{Call: _e.mock.On("UpdateSyncMeta", ctx, s)}
}

func (_c *MockRepository_UpdateSyncMeta_Call) Run(run func(ctx context.Context, s models.SyncMeta)) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SyncMeta))
	})
	return _c
}

func (_c *MockRepository_UpdateSyncMeta_Call) Return(_a0 error) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateSyncMeta_Call) RunAndReturn(run func(context.Context, models.SyncMeta) error) *MockRepository_UpdateSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNotifications provides a mock function with given fields: ctx, notifications
func (_m *MockRepository) UpsertNotifications(ctx context.Context, notifications []triage.Notification) error {
	ret := _m.Called(ctx, notifications)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []triage.Notification) error); ok {
		r0 = rf(ctx, notifications)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpsertNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNotifications'
type MockRepository_UpsertNotifications_Call struct {
	*mock.Call
}

// UpsertNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []triage.Notification
func (_e *MockRepository_Expecter) UpsertNotifications(ctx interface{}, notifications interface{}) *MockRepository_UpsertNotifications_Call {
	return &MockRepository_UpsertNotifications_Call{Call: _e.mock.On("UpsertNotifications", ctx, notifications)}
}

func (_c *MockRepository_UpsertNotifications_Call) Run(run func(ctx context.Context, notifications []triage.Notification)) *MockRepository_UpsertNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]triage.Notification))
	})
	return _c
}

func (_c *MockRepository_UpsertNotifications_Call) Return(_a0 error) *MockRepository_UpsertNotifications_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpsertNotifications_Call) RunAndReturn(run func(context.Context, []triage.Notification) error) *MockRepository_UpsertNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
