// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/hirakiuc/gh-orbit/internal/github"
	"github.com/hirakiuc/gh-orbit/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BaseURL provides a mock function for the type MockClient
func (_mock *MockClient) BaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_BaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseURL'
type MockClient_BaseURL_Call struct {
	*mock.Call
}

// BaseURL is a helper method to define mock.On call
func (_e *MockClient_Expecter) BaseURL() *MockClient_BaseURL_Call {
	return &MockClient_BaseURL_Call{Call: _e.mock.On("BaseURL")}
}

func (_c *MockClient_BaseURL_Call) Run(run func()) *MockClient_BaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_BaseURL_Call) Return(s string) *MockClient_BaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_BaseURL_Call) RunAndReturn(run func() string) *MockClient_BaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function for the type MockClient
func (_mock *MockClient) CurrentUser(ctx context.Context) (*github.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *github.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*github.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *github.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type MockClient_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) CurrentUser(ctx any) *MockClient_CurrentUser_Call {
	return &MockClient_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *MockClient_CurrentUser_Call) Run(run func(ctx context.Context)) *MockClient_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_CurrentUser_Call) Return(user *github.User, err error) *MockClient_CurrentUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_CurrentUser_Call) RunAndReturn(run func(ctx context.Context) (*github.User, error)) *MockClient_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// GQL provides a mock function for the type MockClient
func (_mock *MockClient) GQL() github.GraphQLClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GQL")
	}

	var r0 github.GraphQLClient
	if returnFunc, ok := ret.Get(0).(func() github.GraphQLClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.GraphQLClient)
		}
	}
	return r0
}

// MockClient_GQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GQL'
type MockClient_GQL_Call struct {
	*mock.Call
}

// GQL is a helper method to define mock.On call
func (_e *MockClient_Expecter) GQL() *MockClient_GQL_Call {
	return &MockClient_GQL_Call{Call: _e.mock.On("GQL")}
}

func (_c *MockClient_GQL_Call) Run(run func()) *MockClient_GQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GQL_Call) Return(graphQLClient github.GraphQLClient) *MockClient_GQL_Call {
	_c.Call.Return(graphQLClient)
	return _c
}

func (_c *MockClient_GQL_Call) RunAndReturn(run func() github.GraphQLClient) *MockClient_GQL_Call {
	_c.Call.Return(run)
	return _c
}

// HTTP provides a mock function for the type MockClient
func (_mock *MockClient) HTTP() *http.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTP")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// MockClient_HTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTP'
type MockClient_HTTP_Call struct {
	*mock.Call
}

// HTTP is a helper method to define mock.On call
func (_e *MockClient_Expecter) HTTP() *MockClient_HTTP_Call {
	return &MockClient_HTTP_Call{Call: _e.mock.On("HTTP")}
}

func (_c *MockClient_HTTP_Call) Run(run func()) *MockClient_HTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_HTTP_Call) Return(client *http.Client) *MockClient_HTTP_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClient_HTTP_Call) RunAndReturn(run func() *http.Client) *MockClient_HTTP_Call {
	_c.Call.Return(run)
	return _c
}

// MarkThreadAsRead provides a mock function for the type MockClient
func (_mock *MockClient) MarkThreadAsRead(ctx context.Context, threadID string) error {
	ret := _mock.Called(ctx, threadID)

	if len(ret) == 0 {
		panic("no return value specified for MarkThreadAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, threadID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_MarkThreadAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkThreadAsRead'
type MockClient_MarkThreadAsRead_Call struct {
	*mock.Call
}

// MarkThreadAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - threadID string
func (_e *MockClient_Expecter) MarkThreadAsRead(ctx any, threadID any) *MockClient_MarkThreadAsRead_Call {
	return &MockClient_MarkThreadAsRead_Call{Call: _e.mock.On("MarkThreadAsRead", ctx, threadID)}
}

func (_c *MockClient_MarkThreadAsRead_Call) Run(run func(ctx context.Context, threadID string)) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_MarkThreadAsRead_Call) Return(err error) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_MarkThreadAsRead_Call) RunAndReturn(run func(ctx context.Context, threadID string) error) *MockClient_MarkThreadAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// REST provides a mock function for the type MockClient
func (_mock *MockClient) REST() github.RESTClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for REST")
	}

	var r0 github.RESTClient
	if returnFunc, ok := ret.Get(0).(func() github.RESTClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.RESTClient)
		}
	}
	return r0
}

// MockClient_REST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'REST'
type MockClient_REST_Call struct {
	*mock.Call
}

// REST is a helper method to define mock.On call
func (_e *MockClient_Expecter) REST() *MockClient_REST_Call {
	return &MockClient_REST_Call{Call: _e.mock.On("REST")}
}

func (_c *MockClient_REST_Call) Run(run func()) *MockClient_REST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_REST_Call) Return(rESTClient github.RESTClient) *MockClient_REST_Call {
	_c.Call.Return(rESTClient)
	return _c
}

func (_c *MockClient_REST_Call) RunAndReturn(run func() github.RESTClient) *MockClient_REST_Call {
	_c.Call.Return(run)
	return _c
}

// ReportRateLimit provides a mock function for the type MockClient
func (_mock *MockClient) ReportRateLimit(info models.RateLimitInfo) {
	_mock.Called(info)
	return
}

// MockClient_ReportRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportRateLimit'
type MockClient_ReportRateLimit_Call struct {
	*mock.Call
}

// ReportRateLimit is a helper method to define mock.On call
//   - info models.RateLimitInfo
func (_e *MockClient_Expecter) ReportRateLimit(info any) *MockClient_ReportRateLimit_Call {
	return &MockClient_ReportRateLimit_Call{Call: _e.mock.On("ReportRateLimit", info)}
}

func (_c *MockClient_ReportRateLimit_Call) Run(run func(info models.RateLimitInfo)) *MockClient_ReportRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.RateLimitInfo
		if args[0] != nil {
			arg0 = args[0].(models.RateLimitInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ReportRateLimit_Call) Return() *MockClient_ReportRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_ReportRateLimit_Call) RunAndReturn(run func(info models.RateLimitInfo)) *MockClient_ReportRateLimit_Call {
	_c.Run(run)
	return _c
}

// SetRateLimitReporter provides a mock function for the type MockClient
func (_mock *MockClient) SetRateLimitReporter(fn func(models.RateLimitInfo)) {
	_mock.Called(fn)
	return
}

// MockClient_SetRateLimitReporter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRateLimitReporter'
type MockClient_SetRateLimitReporter_Call struct {
	*mock.Call
}

// SetRateLimitReporter is a helper method to define mock.On call
//   - fn func(models.RateLimitInfo)
func (_e *MockClient_Expecter) SetRateLimitReporter(fn any) *MockClient_SetRateLimitReporter_Call {
	return &MockClient_SetRateLimitReporter_Call{Call: _e.mock.On("SetRateLimitReporter", fn)}
}

func (_c *MockClient_SetRateLimitReporter_Call) Run(run func(fn func(models.RateLimitInfo))) *MockClient_SetRateLimitReporter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(models.RateLimitInfo)
		if args[0] != nil {
			arg0 = args[0].(func(models.RateLimitInfo))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_SetRateLimitReporter_Call) Return() *MockClient_SetRateLimitReporter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetRateLimitReporter_Call) RunAndReturn(run func(fn func(models.RateLimitInfo))) *MockClient_SetRateLimitReporter_Call {
	_c.Run(run)
	return _c
}
