// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEnrichmentRepository creates a new instance of MockEnrichmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrichmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrichmentRepository {
	mock := &MockEnrichmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnrichmentRepository is an autogenerated mock type for the EnrichmentRepository type
type MockEnrichmentRepository struct {
	mock.Mock
}

type MockEnrichmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrichmentRepository) EXPECT() *MockEnrichmentRepository_Expecter {
	return &MockEnrichmentRepository_Expecter{mock: &_m.Mock}
}

// EnrichNotification provides a mock function for the type MockEnrichmentRepository
func (_mock *MockEnrichmentRepository) EnrichNotification(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error {
	ret := _mock.Called(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for EnrichNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnrichmentRepository_EnrichNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichNotification'
type MockEnrichmentRepository_EnrichNotification_Call struct {
	*mock.Call
}

// EnrichNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - nodeID string
//   - body string
//   - author string
//   - htmlURL string
//   - resourceState string
//   - resourceSubState string
func (_e *MockEnrichmentRepository_Expecter) EnrichNotification(ctx interface{}, id interface{}, nodeID interface{}, body interface{}, author interface{}, htmlURL interface{}, resourceState interface{}, resourceSubState interface{}) *MockEnrichmentRepository_EnrichNotification_Call {
	return &MockEnrichmentRepository_EnrichNotification_Call{Call: _e.mock.On("EnrichNotification", ctx, id, nodeID, body, author, htmlURL, resourceState, resourceSubState)}
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) Run(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string)) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) Return(err error) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnrichmentRepository_EnrichNotification_Call) RunAndReturn(run func(ctx context.Context, id string, nodeID string, body string, author string, htmlURL string, resourceState string, resourceSubState string) error) *MockEnrichmentRepository_EnrichNotification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceStateByNodeID provides a mock function for the type MockEnrichmentRepository
func (_mock *MockEnrichmentRepository) UpdateResourceStateByNodeID(ctx context.Context, nodeID string, state string, resourceSubState string) error {
	ret := _mock.Called(ctx, nodeID, state, resourceSubState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceStateByNodeID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, nodeID, state, resourceSubState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnrichmentRepository_UpdateResourceStateByNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceStateByNodeID'
type MockEnrichmentRepository_UpdateResourceStateByNodeID_Call struct {
	*mock.Call
}

// UpdateResourceStateByNodeID is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
//   - state string
//   - resourceSubState string
func (_e *MockEnrichmentRepository_Expecter) UpdateResourceStateByNodeID(ctx interface{}, nodeID interface{}, state interface{}, resourceSubState interface{}) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	return &MockEnrichmentRepository_UpdateResourceStateByNodeID_Call{Call: _e.mock.On("UpdateResourceStateByNodeID", ctx, nodeID, state, resourceSubState)}
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) Run(run func(ctx context.Context, nodeID string, state string, resourceSubState string)) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) Return(err error) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call) RunAndReturn(run func(ctx context.Context, nodeID string, state string, resourceSubState string) error) *MockEnrichmentRepository_UpdateResourceStateByNodeID_Call {
	_c.Call.Return(run)
	return _c
}
