// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Notify(ctx context.Context, title string, subtitle string, body string, url string, priority int) error {
	ret := _mock.Called(ctx, title, subtitle, body, url, priority)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) error); ok {
		r0 = returnFunc(ctx, title, subtitle, body, url, priority)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - subtitle string
//   - body string
//   - url string
//   - priority int
func (_e *MockNotifier_Expecter) Notify(ctx any, title any, subtitle any, body any, url any, priority any) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", ctx, title, subtitle, body, url, priority)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(ctx context.Context, title string, subtitle string, body string, url string, priority int)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(err error) *MockNotifier_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(ctx context.Context, title string, subtitle string, body string, url string, priority int) error) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockNotifier_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockNotifier_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotifier_Expecter) Shutdown(ctx any) *MockNotifier_Shutdown_Call {
	return &MockNotifier_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockNotifier_Shutdown_Call) Run(run func(ctx context.Context)) *MockNotifier_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_Shutdown_Call) Return() *MockNotifier_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockNotifier_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Status() types.BridgeStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 types.BridgeStatus
	if returnFunc, ok := ret.Get(0).(func() types.BridgeStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(types.BridgeStatus)
	}
	return r0
}

// MockNotifier_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockNotifier_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Status() *MockNotifier_Status_Call {
	return &MockNotifier_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockNotifier_Status_Call) Run(run func()) *MockNotifier_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Status_Call) Return(bridgeStatus types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(bridgeStatus)
	return _c
}

func (_c *MockNotifier_Status_Call) RunAndReturn(run func() types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(run)
	return _c
}
