// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: ctx, title, subtitle, body, url, priority
func (_m *MockNotifier) Notify(ctx context.Context, title string, subtitle string, body string, url string, priority int) error {
	ret := _m.Called(ctx, title, subtitle, body, url, priority)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) error); ok {
		r0 = rf(ctx, title, subtitle, body, url, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - subtitle string
//   - body string
//   - url string
//   - priority int
func (_e *MockNotifier_Expecter) Notify(ctx interface{}, title interface{}, subtitle interface{}, body interface{}, url interface{}, priority interface{}) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", ctx, title, subtitle, body, url, priority)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(ctx context.Context, title string, subtitle string, body string, url string, priority int)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(_a0 error) *MockNotifier_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(context.Context, string, string, string, string, int) error) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockNotifier) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// MockNotifier_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockNotifier_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotifier_Expecter) Shutdown(ctx interface{}) *MockNotifier_Shutdown_Call {
	return &MockNotifier_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockNotifier_Shutdown_Call) Run(run func(ctx context.Context)) *MockNotifier_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNotifier_Shutdown_Call) Return() *MockNotifier_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Shutdown_Call) RunAndReturn(run func(context.Context)) *MockNotifier_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockNotifier) Status() types.BridgeStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 types.BridgeStatus
	if rf, ok := ret.Get(0).(func() types.BridgeStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BridgeStatus)
	}

	return r0
}

// MockNotifier_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockNotifier_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Status() *MockNotifier_Status_Call {
	return &MockNotifier_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockNotifier_Status_Call) Run(run func()) *MockNotifier_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Status_Call) Return(_a0 types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Status_Call) RunAndReturn(run func() types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
