// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGraphQLClient is an autogenerated mock type for the GraphQLClient type
type MockGraphQLClient struct {
	mock.Mock
}

type MockGraphQLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphQLClient) EXPECT() *MockGraphQLClient_Expecter {
	return &MockGraphQLClient_Expecter{mock: &_m.Mock}
}

// DoWithContext provides a mock function with given fields: ctx, query, variables, response
func (_m *MockGraphQLClient) DoWithContext(ctx context.Context, query string, variables map[string]interface{}, response interface{}) error {
	ret := _m.Called(ctx, query, variables, response)

	if len(ret) == 0 {
		panic("no return value specified for DoWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, interface{}) error); ok {
		r0 = rf(ctx, query, variables, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGraphQLClient_DoWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithContext'
type MockGraphQLClient_DoWithContext_Call struct {
	*mock.Call
}

// DoWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - variables map[string]interface{}
//   - response interface{}
func (_e *MockGraphQLClient_Expecter) DoWithContext(ctx interface{}, query interface{}, variables interface{}, response interface{}) *MockGraphQLClient_DoWithContext_Call {
	return &MockGraphQLClient_DoWithContext_Call{Call: _e.mock.On("DoWithContext", ctx, query, variables, response)}
}

func (_c *MockGraphQLClient_DoWithContext_Call) Run(run func(ctx context.Context, query string, variables map[string]interface{}, response interface{})) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *MockGraphQLClient_DoWithContext_Call) Return(_a0 error) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGraphQLClient_DoWithContext_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, interface{}) error) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGraphQLClient creates a new instance of MockGraphQLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphQLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphQLClient {
	mock := &MockGraphQLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
