// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphQLClient creates a new instance of MockGraphQLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphQLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphQLClient {
	mock := &MockGraphQLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphQLClient is an autogenerated mock type for the GraphQLClient type
type MockGraphQLClient struct {
	mock.Mock
}

type MockGraphQLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphQLClient) EXPECT() *MockGraphQLClient_Expecter {
	return &MockGraphQLClient_Expecter{mock: &_m.Mock}
}

// DoWithContext provides a mock function for the type MockGraphQLClient
func (_mock *MockGraphQLClient) DoWithContext(ctx context.Context, query string, variables map[string]any, response any) error {
	ret := _mock.Called(ctx, query, variables, response)

	if len(ret) == 0 {
		panic("no return value specified for DoWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any, any) error); ok {
		r0 = returnFunc(ctx, query, variables, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphQLClient_DoWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithContext'
type MockGraphQLClient_DoWithContext_Call struct {
	*mock.Call
}

// DoWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - variables map[string]any
//   - response any
func (_e *MockGraphQLClient_Expecter) DoWithContext(ctx any, query any, variables any, response any) *MockGraphQLClient_DoWithContext_Call {
	return &MockGraphQLClient_DoWithContext_Call{Call: _e.mock.On("DoWithContext", ctx, query, variables, response)}
}

func (_c *MockGraphQLClient_DoWithContext_Call) Run(run func(ctx context.Context, query string, variables map[string]any, response any)) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGraphQLClient_DoWithContext_Call) Return(err error) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphQLClient_DoWithContext_Call) RunAndReturn(run func(ctx context.Context, query string, variables map[string]any, response any) error) *MockGraphQLClient_DoWithContext_Call {
	_c.Call.Return(run)
	return _c
}
