// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/hirakiuc/gh-orbit/internal/github"
	mock "github.com/stretchr/testify/mock"

	types "github.com/hirakiuc/gh-orbit/internal/types"
)

// MockAlerter is an autogenerated mock type for the Alerter type
type MockAlerter struct {
	mock.Mock
}

type MockAlerter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlerter) EXPECT() *MockAlerter_Expecter {
	return &MockAlerter_Expecter{mock: &_m.Mock}
}

// ActiveTierInfo provides a mock function with no fields
func (_m *MockAlerter) ActiveTierInfo() (string, types.BridgeStatus) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ActiveTierInfo")
	}

	var r0 string
	var r1 types.BridgeStatus
	if rf, ok := ret.Get(0).(func() (string, types.BridgeStatus)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() types.BridgeStatus); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(types.BridgeStatus)
	}

	return r0, r1
}

// MockAlerter_ActiveTierInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveTierInfo'
type MockAlerter_ActiveTierInfo_Call struct {
	*mock.Call
}

// ActiveTierInfo is a helper method to define mock.On call
func (_e *MockAlerter_Expecter) ActiveTierInfo() *MockAlerter_ActiveTierInfo_Call {
	return &MockAlerter_ActiveTierInfo_Call{Call: _e.mock.On("ActiveTierInfo")}
}

func (_c *MockAlerter_ActiveTierInfo_Call) Run(run func()) *MockAlerter_ActiveTierInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlerter_ActiveTierInfo_Call) Return(_a0 string, _a1 types.BridgeStatus) *MockAlerter_ActiveTierInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlerter_ActiveTierInfo_Call) RunAndReturn(run func() (string, types.BridgeStatus)) *MockAlerter_ActiveTierInfo_Call {
	_c.Call.Return(run)
	return _c
}

// BridgeStatus provides a mock function with no fields
func (_m *MockAlerter) BridgeStatus() types.BridgeStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BridgeStatus")
	}

	var r0 types.BridgeStatus
	if rf, ok := ret.Get(0).(func() types.BridgeStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BridgeStatus)
	}

	return r0
}

// MockAlerter_BridgeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BridgeStatus'
type MockAlerter_BridgeStatus_Call struct {
	*mock.Call
}

// BridgeStatus is a helper method to define mock.On call
func (_e *MockAlerter_Expecter) BridgeStatus() *MockAlerter_BridgeStatus_Call {
	return &MockAlerter_BridgeStatus_Call{Call: _e.mock.On("BridgeStatus")}
}

func (_c *MockAlerter_BridgeStatus_Call) Run(run func()) *MockAlerter_BridgeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlerter_BridgeStatus_Call) Return(_a0 types.BridgeStatus) *MockAlerter_BridgeStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlerter_BridgeStatus_Call) RunAndReturn(run func() types.BridgeStatus) *MockAlerter_BridgeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: ctx, n
func (_m *MockAlerter) Notify(ctx context.Context, n github.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, github.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlerter_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockAlerter_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - n github.Notification
func (_e *MockAlerter_Expecter) Notify(ctx interface{}, n interface{}) *MockAlerter_Notify_Call {
	return &MockAlerter_Notify_Call{Call: _e.mock.On("Notify", ctx, n)}
}

func (_c *MockAlerter_Notify_Call) Run(run func(ctx context.Context, n github.Notification)) *MockAlerter_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(github.Notification))
	})
	return _c
}

func (_c *MockAlerter_Notify_Call) Return(_a0 error) *MockAlerter_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlerter_Notify_Call) RunAndReturn(run func(context.Context, github.Notification) error) *MockAlerter_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockAlerter) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// MockAlerter_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockAlerter_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlerter_Expecter) Shutdown(ctx interface{}) *MockAlerter_Shutdown_Call {
	return &MockAlerter_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockAlerter_Shutdown_Call) Run(run func(ctx context.Context)) *MockAlerter_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlerter_Shutdown_Call) Return() *MockAlerter_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_Shutdown_Call) RunAndReturn(run func(context.Context)) *MockAlerter_Shutdown_Call {
	_c.Run(run)
	return _c
}

// SyncStart provides a mock function with given fields: ctx
func (_m *MockAlerter) SyncStart(ctx context.Context) {
	_m.Called(ctx)
}

// MockAlerter_SyncStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncStart'
type MockAlerter_SyncStart_Call struct {
	*mock.Call
}

// SyncStart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlerter_Expecter) SyncStart(ctx interface{}) *MockAlerter_SyncStart_Call {
	return &MockAlerter_SyncStart_Call{Call: _e.mock.On("SyncStart", ctx)}
}

func (_c *MockAlerter_SyncStart_Call) Run(run func(ctx context.Context)) *MockAlerter_SyncStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlerter_SyncStart_Call) Return() *MockAlerter_SyncStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_SyncStart_Call) RunAndReturn(run func(context.Context)) *MockAlerter_SyncStart_Call {
	_c.Run(run)
	return _c
}

// TestNotify provides a mock function with given fields: ctx, title, subtitle, body
func (_m *MockAlerter) TestNotify(ctx context.Context, title string, subtitle string, body string) error {
	ret := _m.Called(ctx, title, subtitle, body)

	if len(ret) == 0 {
		panic("no return value specified for TestNotify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, title, subtitle, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlerter_TestNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestNotify'
type MockAlerter_TestNotify_Call struct {
	*mock.Call
}

// TestNotify is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - subtitle string
//   - body string
func (_e *MockAlerter_Expecter) TestNotify(ctx interface{}, title interface{}, subtitle interface{}, body interface{}) *MockAlerter_TestNotify_Call {
	return &MockAlerter_TestNotify_Call{Call: _e.mock.On("TestNotify", ctx, title, subtitle, body)}
}

func (_c *MockAlerter_TestNotify_Call) Run(run func(ctx context.Context, title string, subtitle string, body string)) *MockAlerter_TestNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAlerter_TestNotify_Call) Return(_a0 error) *MockAlerter_TestNotify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlerter_TestNotify_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAlerter_TestNotify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlerter creates a new instance of MockAlerter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlerter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlerter {
	mock := &MockAlerter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
