// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	db "github.com/hirakiuc/gh-orbit/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertRepository is an autogenerated mock type for the AlertRepository type
type MockAlertRepository struct {
	mock.Mock
}

type MockAlertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertRepository) EXPECT() *MockAlertRepository_Expecter {
	return &MockAlertRepository_Expecter{mock: &_m.Mock}
}

// GetBridgeHealth provides a mock function with no fields
func (_m *MockAlertRepository) GetBridgeHealth() (*db.BridgeHealth, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *db.BridgeHealth
	var r1 error
	if rf, ok := ret.Get(0).(func() (*db.BridgeHealth, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *db.BridgeHealth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BridgeHealth)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_GetBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeHealth'
type MockAlertRepository_GetBridgeHealth_Call struct {
	*mock.Call
}

// GetBridgeHealth is a helper method to define mock.On call
func (_e *MockAlertRepository_Expecter) GetBridgeHealth() *MockAlertRepository_GetBridgeHealth_Call {
	return &MockAlertRepository_GetBridgeHealth_Call{Call: _e.mock.On("GetBridgeHealth")}
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Run(run func()) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Return(_a0 *db.BridgeHealth, _a1 error) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) RunAndReturn(run func() (*db.BridgeHealth, error)) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotification provides a mock function with given fields: id
func (_m *MockAlertRepository) GetNotification(id string) (*db.NotificationWithState, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NotificationWithState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NotificationWithState); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockAlertRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - id string
func (_e *MockAlertRepository_Expecter) GetNotification(id interface{}) *MockAlertRepository_GetNotification_Call {
	return &MockAlertRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", id)}
}

func (_c *MockAlertRepository_GetNotification_Call) Run(run func(id string)) *MockAlertRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAlertRepository_GetNotification_Call) Return(_a0 *db.NotificationWithState, _a1 error) *MockAlertRepository_GetNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_GetNotification_Call) RunAndReturn(run func(string) (*db.NotificationWithState, error)) *MockAlertRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function with no fields
func (_m *MockAlertRepository) ListNotifications() ([]db.NotificationWithState, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]db.NotificationWithState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []db.NotificationWithState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockAlertRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
func (_e *MockAlertRepository_Expecter) ListNotifications() *MockAlertRepository_ListNotifications_Call {
	return &MockAlertRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications")}
}

func (_c *MockAlertRepository_ListNotifications_Call) Run(run func()) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) Return(_a0 []db.NotificationWithState, _a1 error) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) RunAndReturn(run func() ([]db.NotificationWithState, error)) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBridgeHealth provides a mock function with given fields: h
func (_m *MockAlertRepository) UpdateBridgeHealth(h db.BridgeHealth) error {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.BridgeHealth) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRepository_UpdateBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBridgeHealth'
type MockAlertRepository_UpdateBridgeHealth_Call struct {
	*mock.Call
}

// UpdateBridgeHealth is a helper method to define mock.On call
//   - h db.BridgeHealth
func (_e *MockAlertRepository_Expecter) UpdateBridgeHealth(h interface{}) *MockAlertRepository_UpdateBridgeHealth_Call {
	return &MockAlertRepository_UpdateBridgeHealth_Call{Call: _e.mock.On("UpdateBridgeHealth", h)}
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Run(run func(h db.BridgeHealth)) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(db.BridgeHealth))
	})
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Return(_a0 error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) RunAndReturn(run func(db.BridgeHealth) error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertRepository creates a new instance of MockAlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertRepository {
	mock := &MockAlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
