// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: title, subtitle, body, url, priority
func (_m *MockNotifier) Notify(title string, subtitle string, body string, url string, priority int) error {
	ret := _m.Called(title, subtitle, body, url, priority)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int) error); ok {
		r0 = rf(title, subtitle, body, url, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - title string
//   - subtitle string
//   - body string
//   - url string
//   - priority int
func (_e *MockNotifier_Expecter) Notify(title interface{}, subtitle interface{}, body interface{}, url interface{}, priority interface{}) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", title, subtitle, body, url, priority)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(title string, subtitle string, body string, url string, priority int)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(_a0 error) *MockNotifier_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(string, string, string, string, int) error) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockNotifier) Ready() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// MockNotifier_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockNotifier_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Ready() *MockNotifier_Ready_Call {
	return &MockNotifier_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockNotifier_Ready_Call) Run(run func()) *MockNotifier_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Ready_Call) Return(_a0 <-chan struct{}) *MockNotifier_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Ready_Call) RunAndReturn(run func() <-chan struct{}) *MockNotifier_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with no fields
func (_m *MockNotifier) Shutdown() {
	_m.Called()
}

// MockNotifier_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockNotifier_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Shutdown() *MockNotifier_Shutdown_Call {
	return &MockNotifier_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockNotifier_Shutdown_Call) Run(run func()) *MockNotifier_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Shutdown_Call) Return() *MockNotifier_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Shutdown_Call) RunAndReturn(run func()) *MockNotifier_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockNotifier) Status() types.BridgeStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 types.BridgeStatus
	if rf, ok := ret.Get(0).(func() types.BridgeStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BridgeStatus)
	}

	return r0
}

// MockNotifier_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockNotifier_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Status() *MockNotifier_Status_Call {
	return &MockNotifier_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockNotifier_Status_Call) Run(run func()) *MockNotifier_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Status_Call) Return(_a0 types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Status_Call) RunAndReturn(run func() types.BridgeStatus) *MockNotifier_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Warmup provides a mock function with no fields
func (_m *MockNotifier) Warmup() {
	_m.Called()
}

// MockNotifier_Warmup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warmup'
type MockNotifier_Warmup_Call struct {
	*mock.Call
}

// Warmup is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Warmup() *MockNotifier_Warmup_Call {
	return &MockNotifier_Warmup_Call{Call: _e.mock.On("Warmup")}
}

func (_c *MockNotifier_Warmup_Call) Run(run func()) *MockNotifier_Warmup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Warmup_Call) Return() *MockNotifier_Warmup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Warmup_Call) RunAndReturn(run func()) *MockNotifier_Warmup_Call {
	_c.Run(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
