// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/hirakiuc/gh-orbit/internal/models"
	mock "github.com/stretchr/testify/mock"

	triage "github.com/hirakiuc/gh-orbit/internal/triage"
)

// MockSyncRepository is an autogenerated mock type for the SyncRepository type
type MockSyncRepository struct {
	mock.Mock
}

type MockSyncRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncRepository) EXPECT() *MockSyncRepository_Expecter {
	return &MockSyncRepository_Expecter{mock: &_m.Mock}
}

// GetNotification provides a mock function with given fields: ctx, id
func (_m *MockSyncRepository) GetNotification(ctx context.Context, id string) (*triage.NotificationWithState, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *triage.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*triage.NotificationWithState, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *triage.NotificationWithState); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*triage.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockSyncRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSyncRepository_Expecter) GetNotification(ctx interface{}, id interface{}) *MockSyncRepository_GetNotification_Call {
	return &MockSyncRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", ctx, id)}
}

func (_c *MockSyncRepository_GetNotification_Call) Run(run func(ctx context.Context, id string)) *MockSyncRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSyncRepository_GetNotification_Call) Return(_a0 *triage.NotificationWithState, _a1 error) *MockSyncRepository_GetNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncRepository_GetNotification_Call) RunAndReturn(run func(context.Context, string) (*triage.NotificationWithState, error)) *MockSyncRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncMeta provides a mock function with given fields: ctx, userID, key
func (_m *MockSyncRepository) GetSyncMeta(ctx context.Context, userID string, key string) (*models.SyncMeta, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncMeta")
	}

	var r0 *models.SyncMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.SyncMeta, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.SyncMeta); ok {
		r0 = rf(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SyncMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncRepository_GetSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncMeta'
type MockSyncRepository_GetSyncMeta_Call struct {
	*mock.Call
}

// GetSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *MockSyncRepository_Expecter) GetSyncMeta(ctx interface{}, userID interface{}, key interface{}) *MockSyncRepository_GetSyncMeta_Call {
	return &MockSyncRepository_GetSyncMeta_Call{Call: _e.mock.On("GetSyncMeta", ctx, userID, key)}
}

func (_c *MockSyncRepository_GetSyncMeta_Call) Run(run func(ctx context.Context, userID string, key string)) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSyncRepository_GetSyncMeta_Call) Return(_a0 *models.SyncMeta, _a1 error) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncRepository_GetSyncMeta_Call) RunAndReturn(run func(context.Context, string, string) (*models.SyncMeta, error)) *MockSyncRepository_GetSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotifiedBatch provides a mock function with given fields: ctx, ids
func (_m *MockSyncRepository) MarkNotifiedBatch(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotifiedBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_MarkNotifiedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotifiedBatch'
type MockSyncRepository_MarkNotifiedBatch_Call struct {
	*mock.Call
}

// MarkNotifiedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockSyncRepository_Expecter) MarkNotifiedBatch(ctx interface{}, ids interface{}) *MockSyncRepository_MarkNotifiedBatch_Call {
	return &MockSyncRepository_MarkNotifiedBatch_Call{Call: _e.mock.On("MarkNotifiedBatch", ctx, ids)}
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) Run(run func(ctx context.Context, ids []string)) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) Return(_a0 error) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_MarkNotifiedBatch_Call) RunAndReturn(run func(context.Context, []string) error) *MockSyncRepository_MarkNotifiedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncMeta provides a mock function with given fields: ctx, s
func (_m *MockSyncRepository) UpdateSyncMeta(ctx context.Context, s models.SyncMeta) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SyncMeta) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_UpdateSyncMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncMeta'
type MockSyncRepository_UpdateSyncMeta_Call struct {
	*mock.Call
}

// UpdateSyncMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - s models.SyncMeta
func (_e *MockSyncRepository_Expecter) UpdateSyncMeta(ctx interface{}, s interface{}) *MockSyncRepository_UpdateSyncMeta_Call {
	return &MockSyncRepository_UpdateSyncMeta_Call{Call: _e.mock.On("UpdateSyncMeta", ctx, s)}
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) Run(run func(ctx context.Context, s models.SyncMeta)) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SyncMeta))
	})
	return _c
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) Return(_a0 error) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_UpdateSyncMeta_Call) RunAndReturn(run func(context.Context, models.SyncMeta) error) *MockSyncRepository_UpdateSyncMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNotifications provides a mock function with given fields: ctx, notifications
func (_m *MockSyncRepository) UpsertNotifications(ctx context.Context, notifications []triage.Notification) error {
	ret := _m.Called(ctx, notifications)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []triage.Notification) error); ok {
		r0 = rf(ctx, notifications)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncRepository_UpsertNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNotifications'
type MockSyncRepository_UpsertNotifications_Call struct {
	*mock.Call
}

// UpsertNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []triage.Notification
func (_e *MockSyncRepository_Expecter) UpsertNotifications(ctx interface{}, notifications interface{}) *MockSyncRepository_UpsertNotifications_Call {
	return &MockSyncRepository_UpsertNotifications_Call{Call: _e.mock.On("UpsertNotifications", ctx, notifications)}
}

func (_c *MockSyncRepository_UpsertNotifications_Call) Run(run func(ctx context.Context, notifications []triage.Notification)) *MockSyncRepository_UpsertNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]triage.Notification))
	})
	return _c
}

func (_c *MockSyncRepository_UpsertNotifications_Call) Return(_a0 error) *MockSyncRepository_UpsertNotifications_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncRepository_UpsertNotifications_Call) RunAndReturn(run func(context.Context, []triage.Notification) error) *MockSyncRepository_UpsertNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncRepository creates a new instance of MockSyncRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncRepository {
	mock := &MockSyncRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
