// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockRESTClient is an autogenerated mock type for the RESTClient type
type MockRESTClient struct {
	mock.Mock
}

type MockRESTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRESTClient) EXPECT() *MockRESTClient_Expecter {
	return &MockRESTClient_Expecter{mock: &_m.Mock}
}

// DoWithContext provides a mock function with given fields: ctx, method, path, body, response
func (_m *MockRESTClient) DoWithContext(ctx context.Context, method string, path string, body io.Reader, response interface{}) error {
	ret := _m.Called(ctx, method, path, body, response)

	if len(ret) == 0 {
		panic("no return value specified for DoWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, interface{}) error); ok {
		r0 = rf(ctx, method, path, body, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRESTClient_DoWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithContext'
type MockRESTClient_DoWithContext_Call struct {
	*mock.Call
}

// DoWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - body io.Reader
//   - response interface{}
func (_e *MockRESTClient_Expecter) DoWithContext(ctx interface{}, method interface{}, path interface{}, body interface{}, response interface{}) *MockRESTClient_DoWithContext_Call {
	return &MockRESTClient_DoWithContext_Call{Call: _e.mock.On("DoWithContext", ctx, method, path, body, response)}
}

func (_c *MockRESTClient_DoWithContext_Call) Run(run func(ctx context.Context, method string, path string, body io.Reader, response interface{})) *MockRESTClient_DoWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader), args[4].(interface{}))
	})
	return _c
}

func (_c *MockRESTClient_DoWithContext_Call) Return(_a0 error) *MockRESTClient_DoWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRESTClient_DoWithContext_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, interface{}) error) *MockRESTClient_DoWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRESTClient creates a new instance of MockRESTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRESTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRESTClient {
	mock := &MockRESTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
