// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	tea "charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"

	types "github.com/hirakiuc/gh-orbit/internal/types"
)

// MockEnricher is an autogenerated mock type for the Enricher type
type MockEnricher struct {
	mock.Mock
}

type MockEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnricher) EXPECT() *MockEnricher_Expecter {
	return &MockEnricher_Expecter{mock: &_m.Mock}
}

// FetchDetail provides a mock function with given fields: ctx, u, subjectType
func (_m *MockEnricher) FetchDetail(ctx context.Context, u string, subjectType string) (types.EnrichmentResult, error) {
	ret := _m.Called(ctx, u, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for FetchDetail")
	}

	var r0 types.EnrichmentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (types.EnrichmentResult, error)); ok {
		return rf(ctx, u, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) types.EnrichmentResult); ok {
		r0 = rf(ctx, u, subjectType)
	} else {
		r0 = ret.Get(0).(types.EnrichmentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, u, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnricher_FetchDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDetail'
type MockEnricher_FetchDetail_Call struct {
	*mock.Call
}

// FetchDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - u string
//   - subjectType string
func (_e *MockEnricher_Expecter) FetchDetail(ctx interface{}, u interface{}, subjectType interface{}) *MockEnricher_FetchDetail_Call {
	return &MockEnricher_FetchDetail_Call{Call: _e.mock.On("FetchDetail", ctx, u, subjectType)}
}

func (_c *MockEnricher_FetchDetail_Call) Run(run func(ctx context.Context, u string, subjectType string)) *MockEnricher_FetchDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) Return(_a0 types.EnrichmentResult, _a1 error) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnricher_FetchDetail_Call) RunAndReturn(run func(context.Context, string, string) (types.EnrichmentResult, error)) *MockEnricher_FetchDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FetchHybridBatch provides a mock function with given fields: ctx, notifications
func (_m *MockEnricher) FetchHybridBatch(ctx context.Context, notifications []types.NotificationWithState) map[string]types.EnrichmentResult {
	ret := _m.Called(ctx, notifications)

	if len(ret) == 0 {
		panic("no return value specified for FetchHybridBatch")
	}

	var r0 map[string]types.EnrichmentResult
	if rf, ok := ret.Get(0).(func(context.Context, []types.NotificationWithState) map[string]types.EnrichmentResult); ok {
		r0 = rf(ctx, notifications)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.EnrichmentResult)
		}
	}

	return r0
}

// MockEnricher_FetchHybridBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHybridBatch'
type MockEnricher_FetchHybridBatch_Call struct {
	*mock.Call
}

// FetchHybridBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - notifications []types.NotificationWithState
func (_e *MockEnricher_Expecter) FetchHybridBatch(ctx interface{}, notifications interface{}) *MockEnricher_FetchHybridBatch_Call {
	return &MockEnricher_FetchHybridBatch_Call{Call: _e.mock.On("FetchHybridBatch", ctx, notifications)}
}

func (_c *MockEnricher_FetchHybridBatch_Call) Run(run func(ctx context.Context, notifications []types.NotificationWithState)) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.NotificationWithState))
	})
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) Return(_a0 map[string]types.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnricher_FetchHybridBatch_Call) RunAndReturn(run func(context.Context, []types.NotificationWithState) map[string]types.EnrichmentResult) *MockEnricher_FetchHybridBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnrichmentCmd provides a mock function with given fields: id, u, subjectType, successMsg, errorMsg
func (_m *MockEnricher) GetEnrichmentCmd(id string, u string, subjectType string, successMsg func(types.EnrichmentResult) tea.Msg, errorMsg func(error) tea.Msg) tea.Cmd {
	ret := _m.Called(id, u, subjectType, successMsg, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for GetEnrichmentCmd")
	}

	var r0 tea.Cmd
	if rf, ok := ret.Get(0).(func(string, string, string, func(types.EnrichmentResult) tea.Msg, func(error) tea.Msg) tea.Cmd); ok {
		r0 = rf(id, u, subjectType, successMsg, errorMsg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}

	return r0
}

// MockEnricher_GetEnrichmentCmd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnrichmentCmd'
type MockEnricher_GetEnrichmentCmd_Call struct {
	*mock.Call
}

// GetEnrichmentCmd is a helper method to define mock.On call
//   - id string
//   - u string
//   - subjectType string
//   - successMsg func(types.EnrichmentResult) tea.Msg
//   - errorMsg func(error) tea.Msg
func (_e *MockEnricher_Expecter) GetEnrichmentCmd(id interface{}, u interface{}, subjectType interface{}, successMsg interface{}, errorMsg interface{}) *MockEnricher_GetEnrichmentCmd_Call {
	return &MockEnricher_GetEnrichmentCmd_Call{Call: _e.mock.On("GetEnrichmentCmd", id, u, subjectType, successMsg, errorMsg)}
}

func (_c *MockEnricher_GetEnrichmentCmd_Call) Run(run func(id string, u string, subjectType string, successMsg func(types.EnrichmentResult) tea.Msg, errorMsg func(error) tea.Msg)) *MockEnricher_GetEnrichmentCmd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(func(types.EnrichmentResult) tea.Msg), args[4].(func(error) tea.Msg))
	})
	return _c
}

func (_c *MockEnricher_GetEnrichmentCmd_Call) Return(_a0 tea.Cmd) *MockEnricher_GetEnrichmentCmd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnricher_GetEnrichmentCmd_Call) RunAndReturn(run func(string, string, string, func(types.EnrichmentResult) tea.Msg, func(error) tea.Msg) tea.Cmd) *MockEnricher_GetEnrichmentCmd_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnricher creates a new instance of MockEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnricher {
	mock := &MockEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
