// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertRepository is an autogenerated mock type for the AlertRepository type
type MockAlertRepository struct {
	mock.Mock
}

type MockAlertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertRepository) EXPECT() *MockAlertRepository_Expecter {
	return &MockAlertRepository_Expecter{mock: &_m.Mock}
}

// GetBridgeHealth provides a mock function with given fields: ctx
func (_m *MockAlertRepository) GetBridgeHealth(ctx context.Context) (*types.BridgeHealth, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *types.BridgeHealth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.BridgeHealth, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.BridgeHealth); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.BridgeHealth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_GetBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeHealth'
type MockAlertRepository_GetBridgeHealth_Call struct {
	*mock.Call
}

// GetBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRepository_Expecter) GetBridgeHealth(ctx interface{}) *MockAlertRepository_GetBridgeHealth_Call {
	return &MockAlertRepository_GetBridgeHealth_Call{Call: _e.mock.On("GetBridgeHealth", ctx)}
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Run(run func(ctx context.Context)) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) Return(_a0 *types.BridgeHealth, _a1 error) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_GetBridgeHealth_Call) RunAndReturn(run func(context.Context) (*types.BridgeHealth, error)) *MockAlertRepository_GetBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotification provides a mock function with given fields: ctx, id
func (_m *MockAlertRepository) GetNotification(ctx context.Context, id string) (*types.NotificationWithState, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *types.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.NotificationWithState, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.NotificationWithState); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_GetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotification'
type MockAlertRepository_GetNotification_Call struct {
	*mock.Call
}

// GetNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAlertRepository_Expecter) GetNotification(ctx interface{}, id interface{}) *MockAlertRepository_GetNotification_Call {
	return &MockAlertRepository_GetNotification_Call{Call: _e.mock.On("GetNotification", ctx, id)}
}

func (_c *MockAlertRepository_GetNotification_Call) Run(run func(ctx context.Context, id string)) *MockAlertRepository_GetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAlertRepository_GetNotification_Call) Return(_a0 *types.NotificationWithState, _a1 error) *MockAlertRepository_GetNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_GetNotification_Call) RunAndReturn(run func(context.Context, string) (*types.NotificationWithState, error)) *MockAlertRepository_GetNotification_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function with given fields: ctx
func (_m *MockAlertRepository) ListNotifications(ctx context.Context) ([]types.NotificationWithState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []types.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]types.NotificationWithState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []types.NotificationWithState); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type MockAlertRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRepository_Expecter) ListNotifications(ctx interface{}) *MockAlertRepository_ListNotifications_Call {
	return &MockAlertRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx)}
}

func (_c *MockAlertRepository_ListNotifications_Call) Run(run func(ctx context.Context)) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) Return(_a0 []types.NotificationWithState, _a1 error) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRepository_ListNotifications_Call) RunAndReturn(run func(context.Context) ([]types.NotificationWithState, error)) *MockAlertRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBridgeHealth provides a mock function with given fields: ctx, h
func (_m *MockAlertRepository) UpdateBridgeHealth(ctx context.Context, h types.BridgeHealth) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BridgeHealth) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRepository_UpdateBridgeHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBridgeHealth'
type MockAlertRepository_UpdateBridgeHealth_Call struct {
	*mock.Call
}

// UpdateBridgeHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - h types.BridgeHealth
func (_e *MockAlertRepository_Expecter) UpdateBridgeHealth(ctx interface{}, h interface{}) *MockAlertRepository_UpdateBridgeHealth_Call {
	return &MockAlertRepository_UpdateBridgeHealth_Call{Call: _e.mock.On("UpdateBridgeHealth", ctx, h)}
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Run(run func(ctx context.Context, h types.BridgeHealth)) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.BridgeHealth))
	})
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) Return(_a0 error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRepository_UpdateBridgeHealth_Call) RunAndReturn(run func(context.Context, types.BridgeHealth) error) *MockAlertRepository_UpdateBridgeHealth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertRepository creates a new instance of MockAlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertRepository {
	mock := &MockAlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
