// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	tea "charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"

	uv "github.com/charmbracelet/ultraviolet"
)

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, name, args
func (_m *MockCommandExecutor) Execute(ctx context.Context, name string, args ...string) ([]byte, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return rf(ctx, name, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = rf(ctx, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) Execute(ctx interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_Execute_Call {
	return &MockCommandExecutor_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandExecutor_Execute_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) Return(_a0 []byte, _a1 error) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) RunAndReturn(run func(context.Context, string, ...string) ([]byte, error)) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// InteractiveGH provides a mock function with given fields: callback, args
func (_m *MockCommandExecutor) InteractiveGH(callback func(error) uv.Event, args ...string) tea.Cmd {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, callback)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InteractiveGH")
	}

	var r0 tea.Cmd
	if rf, ok := ret.Get(0).(func(func(error) uv.Event, ...string) tea.Cmd); ok {
		r0 = rf(callback, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}

	return r0
}

// MockCommandExecutor_InteractiveGH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InteractiveGH'
type MockCommandExecutor_InteractiveGH_Call struct {
	*mock.Call
}

// InteractiveGH is a helper method to define mock.On call
//   - callback func(error) uv.Event
//   - args ...string
func (_e *MockCommandExecutor_Expecter) InteractiveGH(callback interface{}, args ...interface{}) *MockCommandExecutor_InteractiveGH_Call {
	return &MockCommandExecutor_InteractiveGH_Call{Call: _e.mock.On("InteractiveGH",
		append([]interface{}{callback}, args...)...)}
}

func (_c *MockCommandExecutor_InteractiveGH_Call) Run(run func(callback func(error) uv.Event, args ...string)) *MockCommandExecutor_InteractiveGH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(func(error) uv.Event), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_InteractiveGH_Call) Return(_a0 tea.Cmd) *MockCommandExecutor_InteractiveGH_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_InteractiveGH_Call) RunAndReturn(run func(func(error) uv.Event, ...string) tea.Cmd) *MockCommandExecutor_InteractiveGH_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, name, args
func (_m *MockCommandExecutor) Run(ctx context.Context, name string, args ...string) error {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = rf(ctx, name, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) Run(ctx interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_Run_Call {
	return &MockCommandExecutor_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandExecutor_Run_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_Run_Call) Return(_a0 error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_Run_Call) RunAndReturn(run func(context.Context, string, ...string) error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
