// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSyncer is an autogenerated mock type for the Syncer type
type MockSyncer struct {
	mock.Mock
}

type MockSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncer) EXPECT() *MockSyncer_Expecter {
	return &MockSyncer_Expecter{mock: &_m.Mock}
}

// BridgeStatus provides a mock function with no fields
func (_m *MockSyncer) BridgeStatus() types.BridgeStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BridgeStatus")
	}

	var r0 types.BridgeStatus
	if rf, ok := ret.Get(0).(func() types.BridgeStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BridgeStatus)
	}

	return r0
}

// MockSyncer_BridgeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BridgeStatus'
type MockSyncer_BridgeStatus_Call struct {
	*mock.Call
}

// BridgeStatus is a helper method to define mock.On call
func (_e *MockSyncer_Expecter) BridgeStatus() *MockSyncer_BridgeStatus_Call {
	return &MockSyncer_BridgeStatus_Call{Call: _e.mock.On("BridgeStatus")}
}

func (_c *MockSyncer_BridgeStatus_Call) Run(run func()) *MockSyncer_BridgeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSyncer_BridgeStatus_Call) Return(_a0 types.BridgeStatus) *MockSyncer_BridgeStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncer_BridgeStatus_Call) RunAndReturn(run func() types.BridgeStatus) *MockSyncer_BridgeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockSyncer) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// MockSyncer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockSyncer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSyncer_Expecter) Shutdown(ctx interface{}) *MockSyncer_Shutdown_Call {
	return &MockSyncer_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockSyncer_Shutdown_Call) Run(run func(ctx context.Context)) *MockSyncer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSyncer_Shutdown_Call) Return() *MockSyncer_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSyncer_Shutdown_Call) RunAndReturn(run func(context.Context)) *MockSyncer_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Sync provides a mock function with given fields: ctx, userID, force
func (_m *MockSyncer) Sync(ctx context.Context, userID string, force bool) (types.RateLimitInfo, error) {
	ret := _m.Called(ctx, userID, force)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 types.RateLimitInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (types.RateLimitInfo, error)); ok {
		return rf(ctx, userID, force)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) types.RateLimitInfo); ok {
		r0 = rf(ctx, userID, force)
	} else {
		r0 = ret.Get(0).(types.RateLimitInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSyncer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - force bool
func (_e *MockSyncer_Expecter) Sync(ctx interface{}, userID interface{}, force interface{}) *MockSyncer_Sync_Call {
	return &MockSyncer_Sync_Call{Call: _e.mock.On("Sync", ctx, userID, force)}
}

func (_c *MockSyncer_Sync_Call) Run(run func(ctx context.Context, userID string, force bool)) *MockSyncer_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockSyncer_Sync_Call) Return(_a0 types.RateLimitInfo, _a1 error) *MockSyncer_Sync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncer_Sync_Call) RunAndReturn(run func(context.Context, string, bool) (types.RateLimitInfo, error)) *MockSyncer_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncer creates a new instance of MockSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncer {
	mock := &MockSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
