// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	tea "charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockTrafficController is an autogenerated mock type for the TrafficController type
type MockTrafficController struct {
	mock.Mock
}

type MockTrafficController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrafficController) EXPECT() *MockTrafficController_Expecter {
	return &MockTrafficController_Expecter{mock: &_m.Mock}
}

// Remaining provides a mock function with no fields
func (_m *MockTrafficController) Remaining() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remaining")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTrafficController_Remaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remaining'
type MockTrafficController_Remaining_Call struct {
	*mock.Call
}

// Remaining is a helper method to define mock.On call
func (_e *MockTrafficController_Expecter) Remaining() *MockTrafficController_Remaining_Call {
	return &MockTrafficController_Remaining_Call{Call: _e.mock.On("Remaining")}
}

func (_c *MockTrafficController_Remaining_Call) Run(run func()) *MockTrafficController_Remaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrafficController_Remaining_Call) Return(_a0 int) *MockTrafficController_Remaining_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrafficController_Remaining_Call) RunAndReturn(run func() int) *MockTrafficController_Remaining_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockTrafficController) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// MockTrafficController_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTrafficController_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrafficController_Expecter) Shutdown(ctx interface{}) *MockTrafficController_Shutdown_Call {
	return &MockTrafficController_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockTrafficController_Shutdown_Call) Run(run func(ctx context.Context)) *MockTrafficController_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTrafficController_Shutdown_Call) Return() *MockTrafficController_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTrafficController_Shutdown_Call) RunAndReturn(run func(context.Context)) *MockTrafficController_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Submit provides a mock function with given fields: priority, fn
func (_m *MockTrafficController) Submit(priority int, fn func(context.Context) tea.Msg) tea.Cmd {
	ret := _m.Called(priority, fn)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 tea.Cmd
	if rf, ok := ret.Get(0).(func(int, func(context.Context) tea.Msg) tea.Cmd); ok {
		r0 = rf(priority, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}

	return r0
}

// MockTrafficController_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockTrafficController_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - priority int
//   - fn func(context.Context) tea.Msg
func (_e *MockTrafficController_Expecter) Submit(priority interface{}, fn interface{}) *MockTrafficController_Submit_Call {
	return &MockTrafficController_Submit_Call{Call: _e.mock.On("Submit", priority, fn)}
}

func (_c *MockTrafficController_Submit_Call) Run(run func(priority int, fn func(context.Context) tea.Msg)) *MockTrafficController_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(func(context.Context) tea.Msg))
	})
	return _c
}

func (_c *MockTrafficController_Submit_Call) Return(_a0 tea.Cmd) *MockTrafficController_Submit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrafficController_Submit_Call) RunAndReturn(run func(int, func(context.Context) tea.Msg) tea.Cmd) *MockTrafficController_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRateLimit provides a mock function with given fields: ctx, remaining
func (_m *MockTrafficController) UpdateRateLimit(ctx context.Context, remaining int) {
	_m.Called(ctx, remaining)
}

// MockTrafficController_UpdateRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRateLimit'
type MockTrafficController_UpdateRateLimit_Call struct {
	*mock.Call
}

// UpdateRateLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - remaining int
func (_e *MockTrafficController_Expecter) UpdateRateLimit(ctx interface{}, remaining interface{}) *MockTrafficController_UpdateRateLimit_Call {
	return &MockTrafficController_UpdateRateLimit_Call{Call: _e.mock.On("UpdateRateLimit", ctx, remaining)}
}

func (_c *MockTrafficController_UpdateRateLimit_Call) Run(run func(ctx context.Context, remaining int)) *MockTrafficController_UpdateRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTrafficController_UpdateRateLimit_Call) Return() *MockTrafficController_UpdateRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTrafficController_UpdateRateLimit_Call) RunAndReturn(run func(context.Context, int)) *MockTrafficController_UpdateRateLimit_Call {
	_c.Run(run)
	return _c
}

// NewMockTrafficController creates a new instance of MockTrafficController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrafficController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrafficController {
	mock := &MockTrafficController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
