// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/github"
	"github.com/hirakiuc/gh-orbit/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// FetchNotifications provides a mock function for the type MockFetcher
func (_mock *MockFetcher) FetchNotifications(ctx context.Context, meta *models.SyncMeta, force bool) ([]github.Notification, *models.SyncMeta, models.RateLimitInfo, error) {
	ret := _mock.Called(ctx, meta, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchNotifications")
	}

	var r0 []github.Notification
	var r1 *models.SyncMeta
	var r2 models.RateLimitInfo
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SyncMeta, bool) ([]github.Notification, *models.SyncMeta, models.RateLimitInfo, error)); ok {
		return returnFunc(ctx, meta, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SyncMeta, bool) []github.Notification); ok {
		r0 = returnFunc(ctx, meta, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]github.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.SyncMeta, bool) *models.SyncMeta); ok {
		r1 = returnFunc(ctx, meta, force)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.SyncMeta)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.SyncMeta, bool) models.RateLimitInfo); ok {
		r2 = returnFunc(ctx, meta, force)
	} else {
		r2 = ret.Get(2).(models.RateLimitInfo)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, *models.SyncMeta, bool) error); ok {
		r3 = returnFunc(ctx, meta, force)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockFetcher_FetchNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNotifications'
type MockFetcher_FetchNotifications_Call struct {
	*mock.Call
}

// FetchNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *models.SyncMeta
//   - force bool
func (_e *MockFetcher_Expecter) FetchNotifications(ctx any, meta any, force any) *MockFetcher_FetchNotifications_Call {
	return &MockFetcher_FetchNotifications_Call{Call: _e.mock.On("FetchNotifications", ctx, meta, force)}
}

func (_c *MockFetcher_FetchNotifications_Call) Run(run func(ctx context.Context, meta *models.SyncMeta, force bool)) *MockFetcher_FetchNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SyncMeta
		if args[1] != nil {
			arg1 = args[1].(*models.SyncMeta)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFetcher_FetchNotifications_Call) Return(notifications []github.Notification, syncMeta *models.SyncMeta, rateLimitInfo models.RateLimitInfo, err error) *MockFetcher_FetchNotifications_Call {
	_c.Call.Return(notifications, syncMeta, rateLimitInfo, err)
	return _c
}

func (_c *MockFetcher_FetchNotifications_Call) RunAndReturn(run func(ctx context.Context, meta *models.SyncMeta, force bool) ([]github.Notification, *models.SyncMeta, models.RateLimitInfo, error)) *MockFetcher_FetchNotifications_Call {
	_c.Call.Return(run)
	return _c
}
