// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hirakiuc/gh-orbit/internal/models"
	"github.com/hirakiuc/gh-orbit/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrafficController creates a new instance of MockTrafficController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrafficController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrafficController {
	mock := &MockTrafficController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrafficController is an autogenerated mock type for the TrafficController type
type MockTrafficController struct {
	mock.Mock
}

type MockTrafficController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrafficController) EXPECT() *MockTrafficController_Expecter {
	return &MockTrafficController_Expecter{mock: &_m.Mock}
}

// Remaining provides a mock function for the type MockTrafficController
func (_mock *MockTrafficController) Remaining() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remaining")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockTrafficController_Remaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remaining'
type MockTrafficController_Remaining_Call struct {
	*mock.Call
}

// Remaining is a helper method to define mock.On call
func (_e *MockTrafficController_Expecter) Remaining() *MockTrafficController_Remaining_Call {
	return &MockTrafficController_Remaining_Call{Call: _e.mock.On("Remaining")}
}

func (_c *MockTrafficController_Remaining_Call) Run(run func()) *MockTrafficController_Remaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrafficController_Remaining_Call) Return(n int) *MockTrafficController_Remaining_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTrafficController_Remaining_Call) RunAndReturn(run func() int) *MockTrafficController_Remaining_Call {
	_c.Call.Return(run)
	return _c
}

// ReportRateLimit provides a mock function for the type MockTrafficController
func (_mock *MockTrafficController) ReportRateLimit(info models.RateLimitInfo) {
	_mock.Called(info)
	return
}

// MockTrafficController_ReportRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportRateLimit'
type MockTrafficController_ReportRateLimit_Call struct {
	*mock.Call
}

// ReportRateLimit is a helper method to define mock.On call
//   - info models.RateLimitInfo
func (_e *MockTrafficController_Expecter) ReportRateLimit(info interface{}) *MockTrafficController_ReportRateLimit_Call {
	return &MockTrafficController_ReportRateLimit_Call{Call: _e.mock.On("ReportRateLimit", info)}
}

func (_c *MockTrafficController_ReportRateLimit_Call) Run(run func(info models.RateLimitInfo)) *MockTrafficController_ReportRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.RateLimitInfo
		if args[0] != nil {
			arg0 = args[0].(models.RateLimitInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrafficController_ReportRateLimit_Call) Return() *MockTrafficController_ReportRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTrafficController_ReportRateLimit_Call) RunAndReturn(run func(info models.RateLimitInfo)) *MockTrafficController_ReportRateLimit_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockTrafficController
func (_mock *MockTrafficController) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTrafficController_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTrafficController_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrafficController_Expecter) Shutdown(ctx interface{}) *MockTrafficController_Shutdown_Call {
	return &MockTrafficController_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockTrafficController_Shutdown_Call) Run(run func(ctx context.Context)) *MockTrafficController_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrafficController_Shutdown_Call) Return() *MockTrafficController_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTrafficController_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockTrafficController_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Submit provides a mock function for the type MockTrafficController
func (_mock *MockTrafficController) Submit(priority int, fn types.TaskFunc) (<-chan any, error) {
	ret := _mock.Called(priority, fn)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 <-chan any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, types.TaskFunc) (<-chan any, error)); ok {
		return returnFunc(priority, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(int, types.TaskFunc) <-chan any); ok {
		r0 = returnFunc(priority, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, types.TaskFunc) error); ok {
		r1 = returnFunc(priority, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrafficController_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockTrafficController_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - priority int
//   - fn types.TaskFunc
func (_e *MockTrafficController_Expecter) Submit(priority interface{}, fn interface{}) *MockTrafficController_Submit_Call {
	return &MockTrafficController_Submit_Call{Call: _e.mock.On("Submit", priority, fn)}
}

func (_c *MockTrafficController_Submit_Call) Run(run func(priority int, fn types.TaskFunc)) *MockTrafficController_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 types.TaskFunc
		if args[1] != nil {
			arg1 = args[1].(types.TaskFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrafficController_Submit_Call) Return(vCh <-chan any, err error) *MockTrafficController_Submit_Call {
	_c.Call.Return(vCh, err)
	return _c
}

func (_c *MockTrafficController_Submit_Call) RunAndReturn(run func(priority int, fn types.TaskFunc) (<-chan any, error)) *MockTrafficController_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRateLimit provides a mock function for the type MockTrafficController
func (_mock *MockTrafficController) UpdateRateLimit(ctx context.Context, info models.RateLimitInfo) {
	_mock.Called(ctx, info)
	return
}

// MockTrafficController_UpdateRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRateLimit'
type MockTrafficController_UpdateRateLimit_Call struct {
	*mock.Call
}

// UpdateRateLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - info models.RateLimitInfo
func (_e *MockTrafficController_Expecter) UpdateRateLimit(ctx interface{}, info interface{}) *MockTrafficController_UpdateRateLimit_Call {
	return &MockTrafficController_UpdateRateLimit_Call{Call: _e.mock.On("UpdateRateLimit", ctx, info)}
}

func (_c *MockTrafficController_UpdateRateLimit_Call) Run(run func(ctx context.Context, info models.RateLimitInfo)) *MockTrafficController_UpdateRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.RateLimitInfo
		if args[1] != nil {
			arg1 = args[1].(models.RateLimitInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrafficController_UpdateRateLimit_Call) Return() *MockTrafficController_UpdateRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTrafficController_UpdateRateLimit_Call) RunAndReturn(run func(ctx context.Context, info models.RateLimitInfo)) *MockTrafficController_UpdateRateLimit_Call {
	_c.Run(run)
	return _c
}
