linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  misspell:
    locale: US

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - misspell
    - gosec
    - exportloopref
    - bodyclose

run:
  version: "2"
  timeout: 5m
  tests: true
