# Project variables
BINARY_NAME=gh-orbit
CMD_PATH=./cmd/gh-orbit
GOLANGCI_LINT_VERSION=v2.11.3

# Build metadata
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
COMMIT ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)

LDFLAGS=-ldflags "-X github.com/hirakiuc/gh-orbit/internal/buildinfo.Version=$(VERSION) \
                  -X github.com/hirakiuc/gh-orbit/internal/buildinfo.Commit=$(COMMIT) \
                  -X github.com/hirakiuc/gh-orbit/internal/buildinfo.Date=$(DATE)"

# Sandbox-native development environment
PROJECT_TMP ?= $(CURDIR)/tmp
export GOCACHE ?= $(PROJECT_TMP)/go-cache
export GOLANGCI_LINT_CACHE ?= $(PROJECT_TMP)/lint-cache

# OS-specific sed handling
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
    SED_INPLACE := sed -i ''
else
    SED_INPLACE := sed -i
endif

.PHONY: all build release-build test lint vulncheck fmt clean clean-tmp help generate serena coverage coverage-summary artifacts roadmap task reset-task check quality quality-report

all: build

# Unified quality check
check: fmt lint test

# Quantitative Health Check (2026 Standards)
quality: $(PROJECT_TMP)
	@echo "Running quantitative health check..."
	golangci-lint run --default=none -E gocognit,cyclop,maintidx,funlen ./...

# Generate Markdown Health Report for Milestone Issues
quality-report: $(PROJECT_TMP)
	@echo "### 🚀 gh-orbit Maintainability Report ($(DATE))"
	@echo ""
	@echo "| File | Function | Metric | Score | Status |"
	@echo "| :--- | :--- | :--- | :--- | :--- |"
	@golangci-lint run --default=none -E gocognit,cyclop,maintidx,funlen --output.text.path=stdout ./... | \
		sed -E "s/func \`\(\*([^)]+)\)\.([^ \`]+)\`/(\1).\2/g" | \
		sed -E "s/func \`([^ \`]+)\`/\1/g" | \
		sed -E "s/Function '([^']+)'/\1/g" | \
		awk -F': ' '/(cyclomatic|cognitive|too long|too many)/ { \
			file=$$1; \
			split($$2, parts, " "); \
			metric=""; score=""; func_name=""; \
			if (parts[1] == "calculated") { metric=parts[2]; score=parts[5]; func_name=parts[8]; } \
			else if (parts[2] == "complexity") { metric=parts[1]; score=parts[3]; func_name=parts[5]; } \
			else { func_name=parts[1]; metric=parts[3]; score=parts[4]; } \
			gsub(/[()]/, "", score); \
			printf "| %s | %s | %s | %s | 🚩 |\n", file, func_name, metric, score; \
		}' | \
		sort -t'|' -k4 -nr | head -n 20
	@echo ""
	@echo "*Report generated by Gemini CLI*"

# Ensure sandbox directory structure
$(PROJECT_TMP):
	@mkdir -p $(PROJECT_TMP)

build: $(PROJECT_TMP)
	go build $(LDFLAGS) -o bin/$(BINARY_NAME) $(CMD_PATH)
	@if [ "$$(uname)" = "Darwin" ]; then \
		echo "Ad-hoc signing binary for macOS with identifier..."; \
		codesign -f -s - -i gh-orbit-cli bin/$(BINARY_NAME); \
	fi

coverage: $(PROJECT_TMP)
	go test -coverprofile=$(PROJECT_TMP)/coverage.out ./...
	grep -vE "mock_|types/|cmd/gh-orbit" $(PROJECT_TMP)/coverage.out > $(PROJECT_TMP)/coverage.filtered.out
	go tool cover -html=$(PROJECT_TMP)/coverage.filtered.out -o $(PROJECT_TMP)/coverage.html
	@echo "Coverage report generated at $(PROJECT_TMP)/coverage.html (filtered)"

coverage-summary: coverage
	go tool cover -func=$(PROJECT_TMP)/coverage.filtered.out

artifacts: $(PROJECT_TMP)
	@mkdir -p artifacts
	go test -v -artifacts ./...

release-build: $(PROJECT_TMP)
	GOOS=darwin GOARCH=amd64 go build $(LDFLAGS) -o bin/$(BINARY_NAME)-darwin-amd64 $(CMD_PATH)
	@if [ "$$(uname)" = "Darwin" ]; then codesign -f -s - bin/$(BINARY_NAME)-darwin-amd64; fi
	GOOS=darwin GOARCH=arm64 go build $(LDFLAGS) -o bin/$(BINARY_NAME)-darwin-arm64 $(CMD_PATH)
	@if [ "$$(uname)" = "Darwin" ]; then codesign -f -s - bin/$(BINARY_NAME)-darwin-arm64; fi
	GOOS=linux GOARCH=amd64 go build $(LDFLAGS) -o bin/$(BINARY_NAME)-linux-amd64 $(CMD_PATH)
	GOOS=linux GOARCH=arm64 go build $(LDFLAGS) -o bin/$(BINARY_NAME)-linux-arm64 $(CMD_PATH)
	GOOS=windows GOARCH=amd64 go build $(LDFLAGS) -o bin/$(BINARY_NAME)-windows-amd64.exe $(CMD_PATH)

test: $(PROJECT_TMP)
	go test -v ./...

lint: $(PROJECT_TMP)
	golangci-lint run ./...
	$(MAKE) lint-docs

lint-docs:
	markdownlint-cli2

vulncheck: $(PROJECT_TMP)
	govulncheck ./...

fmt: $(PROJECT_TMP)
	gofumpt -l -w .

generate:
	@echo "Generating mocks using packages configuration..."
	@go run github.com/vektra/mockery/v2

serena:
	@echo "Starting Serena MCP server..."
	@uvx --from git+https://github.com/oraios/serena serena start-mcp-server --transport streamable-http --host localhost --port 9121 --project . --context ide-assistant

roadmap:
	@echo "--- Project Roadmap (GitHub Milestones) ---"
	@gh api repos/:owner/:repo/milestones --jq '.[] | "[\(.number)] \(.title) (\(.state)) - \(.open_issues) open, \(.closed_issues) closed"'
	@echo ""
	@echo "--- Active Issues by Milestone ---"
	@gh issue list --search "state:open" --json milestone,number,title --jq '.[] | "[\(.milestone.title)] #\(.number) \(.title)"' | sort

task:
	@if [ -z "$(ID)" ]; then echo "Usage: make task ID=<issue-number>"; exit 1; fi
	@echo "Initializing workbench for Issue #$(ID)..."
	@$(MAKE) reset-task
	@gh issue view "$(ID)" --json title,body,state,labels,milestone --template 'Title: {{.title}}\n\nBody: {{.body}}\n\nLabels: {{range .labels}}{{.name}} {{end}}\nMilestone: {{if .milestone}}{{.milestone.title}}{{else}}None{{end}}\nState: {{.state}}\n' > .agents/issue.md || (echo "Error: Issue #$(ID) not found."; exit 1)
	@echo "Workbench ready: .agents/issue.md initialized. Use the Worker Role to initialize the proposal."

reset-task:
	@echo "Resetting workbench to a neutral state..."
	@printf "No active task" > .agents/issue.md
	@printf "No active task" > .agents/proposal.md
	@printf "No active task" > .agents/feedback.md
	@printf "No active task" > .agents/rfc.md

clean-tmp:
	@echo "Cleaning up local sandbox directory..."
	rm -rf $(PROJECT_TMP)/*
	@touch $(PROJECT_TMP)/.gitkeep

clean: clean-tmp
	rm -rf bin/
	rm -rf internal/api/mocks/
	go clean

help:
	@echo "Available targets:"
	@echo "  build         - Build the local binary"
	@echo "  release-build - Cross-compile for Darwin, Linux, Windows"
	@echo "  generate      - Generate mocks using mockery"
	@echo "  serena        - Start Serena MCP server"
	@echo "  test          - Run tests"
	@echo "  lint          - Run golangci-lint"
	@echo "  vulncheck     - Run govulncheck for security"
	@echo "  fmt           - Format code with gofumpt"
	@echo "  clean         - Remove build artifacts"
	@echo "  clean-tmp     - Remove project-local sandbox files"
	@echo "  check         - Run fmt, lint, and test (fail-fast)"
	@echo "  task          - Initialize workbench for a task (usage: make task ID=<issue-number>)"
	@echo "  reset-task    - Reset workbench files to a neutral state"
	@echo "  quality       - Run quantitative health checks (cyclop, gocognit, funlen, maintidx)"
	@echo "  quality-report- Generate Markdown maintainability report for milestone issues"
