disabled_rules:
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - vertical_whitespace

opt_in_rules:
  - force_unwrapping
  - force_cast
  - strict_concurrency
  - fatal_error_message
  - empty_count
  - contains_over_first_not_nil
  - array_init
  - discouraged_object_literal

force_unwrapping: error
force_cast: error
strict_concurrency: error

included:
  - Sources
  - Tests
