// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	db "github.com/hirakiuc/gh-orbit/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// AlertRepository is an autogenerated mock type for the AlertRepository type
type AlertRepository struct {
	mock.Mock
}

// GetBridgeHealth provides a mock function with no fields
func (_m *AlertRepository) GetBridgeHealth() (*db.BridgeHealth, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeHealth")
	}

	var r0 *db.BridgeHealth
	var r1 error
	if rf, ok := ret.Get(0).(func() (*db.BridgeHealth, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *db.BridgeHealth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BridgeHealth)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotification provides a mock function with given fields: id
func (_m *AlertRepository) GetNotification(id string) (*db.NotificationWithState, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NotificationWithState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NotificationWithState); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNotifications provides a mock function with no fields
func (_m *AlertRepository) ListNotifications() ([]db.NotificationWithState, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]db.NotificationWithState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []db.NotificationWithState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBridgeHealth provides a mock function with given fields: h
func (_m *AlertRepository) UpdateBridgeHealth(h db.BridgeHealth) error {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBridgeHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.BridgeHealth) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAlertRepository creates a new instance of AlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertRepository {
	mock := &AlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
