// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EnrichmentRepository is an autogenerated mock type for the EnrichmentRepository type
type EnrichmentRepository struct {
	mock.Mock
}

// EnrichNotification provides a mock function with given fields: ctx, id, body, author, htmlURL, resourceState
func (_m *EnrichmentRepository) EnrichNotification(ctx context.Context, id string, body string, author string, htmlURL string, resourceState string) error {
	ret := _m.Called(ctx, id, body, author, htmlURL, resourceState)

	if len(ret) == 0 {
		panic("no return value specified for EnrichNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, body, author, htmlURL, resourceState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateResourceStateByNodeID provides a mock function with given fields: ctx, nodeID, state
func (_m *EnrichmentRepository) UpdateResourceStateByNodeID(ctx context.Context, nodeID string, state string) error {
	ret := _m.Called(ctx, nodeID, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceStateByNodeID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEnrichmentRepository creates a new instance of EnrichmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnrichmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnrichmentRepository {
	mock := &EnrichmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
