// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/hirakiuc/gh-orbit/internal/api"

	db "github.com/hirakiuc/gh-orbit/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// FetchNotifications provides a mock function with given fields: ctx, meta, force
func (_m *Fetcher) FetchNotifications(ctx context.Context, meta *db.SyncMeta, force bool) ([]api.GHNotification, *db.SyncMeta, int, error) {
	ret := _m.Called(ctx, meta, force)

	if len(ret) == 0 {
		panic("no return value specified for FetchNotifications")
	}

	var r0 []api.GHNotification
	var r1 *db.SyncMeta
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.SyncMeta, bool) ([]api.GHNotification, *db.SyncMeta, int, error)); ok {
		return rf(ctx, meta, force)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.SyncMeta, bool) []api.GHNotification); ok {
		r0 = rf(ctx, meta, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.GHNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.SyncMeta, bool) *db.SyncMeta); ok {
		r1 = rf(ctx, meta, force)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db.SyncMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *db.SyncMeta, bool) int); ok {
		r2 = rf(ctx, meta, force)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, *db.SyncMeta, bool) error); ok {
		r3 = rf(ctx, meta, force)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
