// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	api "github.com/hirakiuc/gh-orbit/internal/api"
	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// Notify provides a mock function with given fields: title, subtitle, body, url, priority
func (_m *Notifier) Notify(title string, subtitle string, body string, url string, priority int) error {
	ret := _m.Called(title, subtitle, body, url, priority)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int) error); ok {
		r0 = rf(title, subtitle, body, url, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ready provides a mock function with no fields
func (_m *Notifier) Ready() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// Shutdown provides a mock function with no fields
func (_m *Notifier) Shutdown() {
	_m.Called()
}

// Status provides a mock function with no fields
func (_m *Notifier) Status() api.BridgeStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 api.BridgeStatus
	if rf, ok := ret.Get(0).(func() api.BridgeStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(api.BridgeStatus)
	}

	return r0
}

// Warmup provides a mock function with no fields
func (_m *Notifier) Warmup() {
	_m.Called()
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
