// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	db "github.com/hirakiuc/gh-orbit/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// SyncRepository is an autogenerated mock type for the SyncRepository type
type SyncRepository struct {
	mock.Mock
}

// GetNotification provides a mock function with given fields: id
func (_m *SyncRepository) GetNotification(id string) (*db.NotificationWithState, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *db.NotificationWithState
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.NotificationWithState, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *db.NotificationWithState); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NotificationWithState)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncMeta provides a mock function with given fields: userID, key
func (_m *SyncRepository) GetSyncMeta(userID string, key string) (*db.SyncMeta, error) {
	ret := _m.Called(userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncMeta")
	}

	var r0 *db.SyncMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*db.SyncMeta, error)); ok {
		return rf(userID, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) *db.SyncMeta); ok {
		r0 = rf(userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkNotifiedBatch provides a mock function with given fields: ids
func (_m *SyncRepository) MarkNotifiedBatch(ids []string) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotifiedBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSyncMeta provides a mock function with given fields: s
func (_m *SyncRepository) UpdateSyncMeta(s db.SyncMeta) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.SyncMeta) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertNotification provides a mock function with given fields: n
func (_m *SyncRepository) UpsertNotification(n db.Notification) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Notification) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSyncRepository creates a new instance of SyncRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncRepository {
	mock := &SyncRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
